/**
 * Unicode → ASCII mappings by category, each entry `[unicode, ascii]`.
 *
 * Values are the AnyAscii 0.3.3 replacement verbatim (ISC, see
 * LICENSE.anyascii): 1712 entries over the 13 open blocks. Not imported: Latin
 * letters, out-of-scope blocks (scripts included), empty replacements and
 * Discord-style `:shortcode:` labels. See the README section "Table sourcing
 * (AnyAscii)" and scripts/vendor-anyascii.py, which regenerates the tables.
 */

export const PUNCTUATION: Array<[string, string]> = [
  // Dashes
  ["\u2010", "-"], // hyphen (‐)
  ["\u2014", "-"], // em dash (—)
  ["\u2013", "-"], // en dash (–)
  ["\u2012", "-"], // figure dash (‒)
  ["\u2015", "-"], // horizontal bar (―)
  // Ellipsis
  ["\u2026", "..."], // horizontal ellipsis (…)
  // Curly / smart quotes — double
  ["\u201C", '"'], // left double quotation mark (")
  ["\u201D", '"'], // right double quotation mark (")
  ["\u201E", '"'], // double low-9 quotation mark („)
  ["\u201F", '"'], // double high-reversed-9 quotation mark (‟)
  ["\u00AB", "<<"], // left-pointing double angle quotation mark («)
  ["\u00BB", ">>"], // right-pointing double angle quotation mark (»)
  // Curly / smart quotes — single
  ["\u2018", "'"], // left single quotation mark (')
  ["\u2019", "'"], // right single quotation mark (')
  ["\u201A", "'"], // single low-9 quotation mark (‚)
  ["\u201B", "'"], // single high-reversed-9 quotation mark (‛)
  ["\u2039", "<"], // single left-pointing angle quotation mark (‹)
  ["\u203A", ">"], // single right-pointing angle quotation mark (›)
  // Latin-1 punctuation: inside the strip keep-set, so it must be mapped or it
  // leaks through as non-ASCII. NBSP is invisible and desynchronises diffs.
  ["\u00A0", " "], // no-break space ( )
  ["\u00A1", "!"], // inverted exclamation mark (¡)
  ["\u00BF", "?"], // inverted question mark (¿)
  // Miscellaneous punctuation
  ["\u2022", "*"], // bullet (-)
  ["\u2023", "*"], // triangular bullet (‣)
  ["\u25BA", ">"], // black right-pointing pointer (►)
  ["\u2043", "-"], // hyphen bullet (⁃)
  ["\u00B7", "-"], // middle dot (·)
  ["\u2027", "-"], // hyphenation point (‧)
  ["\u2032", "'"], // prime (′)
  ["\u2033", "''"], // double prime (″)
  // U+2030-U+205E tail of General Punctuation, AnyAscii 0.3.3 values.
  ["\u2035", "`"], // reversed prime (‵)
  ["\u2016", "||"], // double vertical line (‖)
  ["\u203C", "!!"], // double exclamation mark (‼)
  ["\u2047", "??"], // double question mark (⁇)
  ["\u2044", "/"], // fraction slash (⁄)
  // Units and legal marks. Latin-1 (U+00A0-U+00FF) already keeps £ ¥ ¢ © ®
  // through the strip; the Letterlike Symbols below take the AnyAscii 0.3.3
  // values verbatim.
  ["\u2122", "TM"], // trade mark sign (™)
  ["\u2117", "(P)"], // sound recording copyright (℗)
  ["\u2103", "C"], // degree celsius (℃)
  ["\u2109", "F"], // degree fahrenheit (℉)
  ["\u2116", "No"], // numero sign (№)
  // AnyAscii wholesale — General Punctuation and Letterlike Symbols.
  ["\u2000", " "], // en quad
  ["\u2001", " "], // em quad
  ["\u2002", " "], // en space
  ["\u2003", " "], // em space
  ["\u2004", " "], // three-per-em space
  ["\u2005", " "], // four-per-em space
  ["\u2006", " "], // six-per-em space
  ["\u2007", " "], // figure space
  ["\u2008", " "], // punctuation space
  ["\u2009", " "], // thin space
  ["\u200a", " "], // hair space
  ["\u2011", "-"], // non-breaking hyphen (‑)
  ["\u2017", "_"], // double low line (‗)
  ["\u2020", "+"], // dagger (†)
  ["\u2021", "++"], // double dagger (‡)
  ["\u2024", "."], // one dot leader (․)
  ["\u2025", ".."], // two dot leader (‥)
  ["\u2028", " "], // line separator
  ["\u2029", " "], // paragraph separator
  ["\u202f", " "], // narrow no-break space
  ["\u2030", "%0"], // per mille sign (‰)
  ["\u2031", "%00"], // per ten thousand sign (‱)
  ["\u2034", "'''"], // triple prime (‴)
  ["\u2036", "``"], // reversed double prime (‶)
  ["\u2037", "```"], // reversed triple prime (‷)
  ["\u2038", "^"], // caret (‸)
  ["\u203b", "*"], // reference mark (※)
  ["\u203d", "!?"], // interrobang (‽)
  ["\u203e", "-"], // overline (‾)
  ["\u203f", "_"], // undertie (‿)
  ["\u2040", "-"], // character tie (⁀)
  ["\u2041", "^"], // caret insertion point (⁁)
  ["\u2042", "***"], // asterism (⁂)
  ["\u2045", "["], // left square bracket with quill (⁅)
  ["\u2046", "]"], // right square bracket with quill (⁆)
  ["\u2048", "?!"], // question exclamation mark (⁈)
  ["\u2049", "!?"], // exclamation question mark (⁉)
  ["\u204a", "&"], // tironian sign et (⁊)
  ["\u204b", "P"], // reversed pilcrow sign (⁋)
  ["\u204c", "<"], // black leftwards bullet (⁌)
  ["\u204d", ">"], // black rightwards bullet (⁍)
  ["\u204e", "*"], // low asterisk (⁎)
  ["\u204f", ";"], // reversed semicolon (⁏)
  ["\u2050", "_"], // close up (⁐)
  ["\u2051", "**"], // two asterisks aligned vertically (⁑)
  ["\u2052", "./."], // commercial minus sign (⁒)
  ["\u2053", "~"], // swung dash (⁓)
  ["\u2054", "_"], // inverted undertie (⁔)
  ["\u2055", "*"], // flower punctuation mark (⁕)
  ["\u2056", ":"], // three dot punctuation (⁖)
  ["\u2057", "''''"], // quadruple prime (⁗)
  ["\u2058", ":"], // four dot punctuation (⁘)
  ["\u2059", "*"], // five dot punctuation (⁙)
  ["\u205a", ":"], // two dot punctuation (⁚)
  ["\u205b", ":"], // four dot mark (⁛)
  ["\u205c", "+"], // dotted cross (⁜)
  ["\u205d", ":"], // tricolon (⁝)
  ["\u205e", ":"], // vertical four dots (⁞)
  ["\u205f", " "], // medium mathematical space
  ["\u2100", "a/c"], // account of (℀)
  ["\u2101", "a/s"], // addressed to the subject (℁)
  ["\u2102", "C"], // double-struck capital c (ℂ)
  ["\u2104", "CL"], // centre line symbol (℄)
  ["\u2105", "c/o"], // care of (℅)
  ["\u2106", "c/u"], // cada una (℆)
  ["\u2107", "E"], // euler constant (ℇ)
  ["\u2108", "g"], // scruple (℈)
  ["\u210a", "g"], // script small g (ℊ)
  ["\u210b", "H"], // script capital h (ℋ)
  ["\u210c", "H"], // black-letter capital h (ℌ)
  ["\u210d", "H"], // double-struck capital h (ℍ)
  ["\u210e", "h"], // planck constant (ℎ)
  ["\u210f", "h"], // planck constant over two pi (ℏ)
  ["\u2110", "I"], // script capital i (ℐ)
  ["\u2111", "I"], // black-letter capital i (ℑ)
  ["\u2112", "L"], // script capital l (ℒ)
  ["\u2113", "l"], // script small l (ℓ)
  ["\u2114", "#"], // l b bar symbol (℔)
  ["\u2115", "N"], // double-struck capital n (ℕ)
  ["\u2118", "p"], // script capital p (℘)
  ["\u2119", "P"], // double-struck capital p (ℙ)
  ["\u211a", "Q"], // double-struck capital q (ℚ)
  ["\u211b", "R"], // script capital r (ℛ)
  ["\u211c", "R"], // black-letter capital r (ℜ)
  ["\u211d", "R"], // double-struck capital r (ℝ)
  ["\u211e", "Rx"], // prescription take (℞)
  ["\u211f", "R"], // response (℟)
  ["\u2120", "SM"], // service mark (℠)
  ["\u2121", "TEL"], // telephone sign (℡)
  ["\u2123", "V"], // versicle (℣)
  ["\u2124", "Z"], // double-struck capital z (ℤ)
  ["\u2125", "oz"], // ounce sign (℥)
  ["\u2126", "Ohm"], // ohm sign (Ω)
  ["\u2127", "Mho"], // inverted ohm sign (℧)
  ["\u2128", "Z"], // black-letter capital z (ℨ)
  ["\u2129", "i"], // turned greek small letter iota (℩)
  ["\u212a", "K"], // kelvin sign (K)
  ["\u212b", "A"], // angstrom sign (Å)
  ["\u212c", "B"], // script capital b (ℬ)
  ["\u212d", "C"], // black-letter capital c (ℭ)
  ["\u212e", "e"], // estimated symbol (℮)
  ["\u212f", "e"], // script small e (ℯ)
  ["\u2130", "E"], // script capital e (ℰ)
  ["\u2131", "F"], // script capital f (ℱ)
  ["\u2132", "F"], // turned capital f (Ⅎ)
  ["\u2133", "M"], // script capital m (ℳ)
  ["\u2134", "o"], // script small o (ℴ)
  ["\u2135", "a"], // alef symbol (ℵ)
  ["\u2136", "b"], // bet symbol (ℶ)
  ["\u2137", "g"], // gimel symbol (ℷ)
  ["\u2138", "d"], // dalet symbol (ℸ)
  ["\u213a", "Q"], // rotated capital q (℺)
  ["\u213b", "FAX"], // facsimile sign (℻)
  ["\u213c", "p"], // double-struck small pi (ℼ)
  ["\u213d", "g"], // double-struck small gamma (ℽ)
  ["\u213e", "G"], // double-struck capital gamma (ℾ)
  ["\u213f", "P"], // double-struck capital pi (ℿ)
  ["\u2140", "S"], // double-struck n-ary summation (⅀)
  ["\u2141", "G"], // turned sans-serif capital g (⅁)
  ["\u2142", "L"], // turned sans-serif capital l (⅂)
  ["\u2143", "L"], // reversed sans-serif capital l (⅃)
  ["\u2144", "Y"], // turned sans-serif capital y (⅄)
  ["\u2145", "D"], // double-struck italic capital d (ⅅ)
  ["\u2146", "d"], // double-struck italic small d (ⅆ)
  ["\u2147", "e"], // double-struck italic small e (ⅇ)
  ["\u2148", "i"], // double-struck italic small i (ⅈ)
  ["\u2149", "j"], // double-struck italic small j (ⅉ)
  ["\u214a", "PL"], // property line (⅊)
  ["\u214b", "&"], // turned ampersand (⅋)
  ["\u214c", "P"], // per sign (⅌)
  ["\u214d", "A/S"], // aktieselskab (⅍)
  ["\u214e", "f"], // turned small f (ⅎ)
  ["\u214f", "Sh"], // symbol for samaritan source (⅏)
];

export const FRAMES: Array<[string, string]> = [
  // Frames — rules, corners, tees and crosses.
  ["\u2500", "-"], // box drawings light horizontal (─)
  ["\u2502", "|"], // box drawings light vertical (│)
  // Box drawing — corners/tees/crosses collapse to "+", rules to "-"/"|".
  // Without this an ASCII-art frame collapsed to "CI ---- passed".
  ["\u250C", "+"], // box drawings light down and right (┌)
  ["\u2510", "+"], // box drawings light down and left (┐)
  ["\u2514", "+"], // box drawings light up and right (└)
  ["\u2518", "+"], // box drawings light up and left (┘)
  ["\u251C", "+"], // box drawings light vertical and right (├)
  ["\u2524", "+"], // box drawings light vertical and left (┤)
  ["\u252C", "+"], // box drawings light down and horizontal (┬)
  ["\u2534", "+"], // box drawings light up and horizontal (┴)
  ["\u253C", "+"], // box drawings light vertical and horizontal (┼)
  ["\u2501", "-"], // box drawings heavy horizontal (━)
  ["\u2503", "|"], // box drawings heavy vertical (┃)
  // AnyAscii wholesale — Box Drawing, heavies and mixed joints.
  ["\u2504", "-"], // box drawings light triple dash horizontal (┄)
  ["\u2505", "-"], // box drawings heavy triple dash horizontal (┅)
  ["\u2506", "|"], // box drawings light triple dash vertical (┆)
  ["\u2507", "|"], // box drawings heavy triple dash vertical (┇)
  ["\u2508", "-"], // box drawings light quadruple dash horizontal (┈)
  ["\u2509", "-"], // box drawings heavy quadruple dash horizontal (┉)
  ["\u250a", "|"], // box drawings light quadruple dash vertical (┊)
  ["\u250b", "|"], // box drawings heavy quadruple dash vertical (┋)
  ["\u250d", "+"], // box drawings down light and right heavy (┍)
  ["\u250e", "+"], // box drawings down heavy and right light (┎)
  ["\u250f", "+"], // box drawings heavy down and right (┏)
  ["\u2511", "+"], // box drawings down light and left heavy (┑)
  ["\u2512", "+"], // box drawings down heavy and left light (┒)
  ["\u2513", "+"], // box drawings heavy down and left (┓)
  ["\u2515", "+"], // box drawings up light and right heavy (┕)
  ["\u2516", "+"], // box drawings up heavy and right light (┖)
  ["\u2517", "+"], // box drawings heavy up and right (┗)
  ["\u2519", "+"], // box drawings up light and left heavy (┙)
  ["\u251a", "+"], // box drawings up heavy and left light (┚)
  ["\u251b", "+"], // box drawings heavy up and left (┛)
  ["\u251d", "+"], // box drawings vertical light and right heavy (┝)
  ["\u251e", "+"], // box drawings up heavy and right down light (┞)
  ["\u251f", "+"], // box drawings down heavy and right up light (┟)
  ["\u2520", "+"], // box drawings vertical heavy and right light (┠)
  ["\u2521", "+"], // box drawings down light and right up heavy (┡)
  ["\u2522", "+"], // box drawings up light and right down heavy (┢)
  ["\u2523", "+"], // box drawings heavy vertical and right (┣)
  ["\u2525", "+"], // box drawings vertical light and left heavy (┥)
  ["\u2526", "+"], // box drawings up heavy and left down light (┦)
  ["\u2527", "+"], // box drawings down heavy and left up light (┧)
  ["\u2528", "+"], // box drawings vertical heavy and left light (┨)
  ["\u2529", "+"], // box drawings down light and left up heavy (┩)
  ["\u252a", "+"], // box drawings up light and left down heavy (┪)
  ["\u252b", "+"], // box drawings heavy vertical and left (┫)
  ["\u252d", "+"], // box drawings left heavy and right down light (┭)
  ["\u252e", "+"], // box drawings right heavy and left down light (┮)
  ["\u252f", "+"], // box drawings down light and horizontal heavy (┯)
  ["\u2530", "+"], // box drawings down heavy and horizontal light (┰)
  ["\u2531", "+"], // box drawings right light and left down heavy (┱)
  ["\u2532", "+"], // box drawings left light and right down heavy (┲)
  ["\u2533", "+"], // box drawings heavy down and horizontal (┳)
  ["\u2535", "+"], // box drawings left heavy and right up light (┵)
  ["\u2536", "+"], // box drawings right heavy and left up light (┶)
  ["\u2537", "+"], // box drawings up light and horizontal heavy (┷)
  ["\u2538", "+"], // box drawings up heavy and horizontal light (┸)
  ["\u2539", "+"], // box drawings right light and left up heavy (┹)
  ["\u253a", "+"], // box drawings left light and right up heavy (┺)
  ["\u253b", "+"], // box drawings heavy up and horizontal (┻)
  ["\u253d", "+"], // box drawings left heavy and right vertical light (┽)
  ["\u253e", "+"], // box drawings right heavy and left vertical light (┾)
  ["\u253f", "+"], // box drawings vertical light and horizontal heavy (┿)
  ["\u2540", "+"], // box drawings up heavy and down horizontal light (╀)
  ["\u2541", "+"], // box drawings down heavy and up horizontal light (╁)
  ["\u2542", "+"], // box drawings vertical heavy and horizontal light (╂)
  ["\u2543", "+"], // box drawings left up heavy and right down light (╃)
  ["\u2544", "+"], // box drawings right up heavy and left down light (╄)
  ["\u2545", "+"], // box drawings left down heavy and right up light (╅)
  ["\u2546", "+"], // box drawings right down heavy and left up light (╆)
  ["\u2547", "+"], // box drawings down light and up horizontal heavy (╇)
  ["\u2548", "+"], // box drawings up light and down horizontal heavy (╈)
  ["\u2549", "+"], // box drawings right light and left vertical heavy (╉)
  ["\u254a", "+"], // box drawings left light and right vertical heavy (╊)
  ["\u254b", "+"], // box drawings heavy vertical and horizontal (╋)
  ["\u254c", "-"], // box drawings light double dash horizontal (╌)
  ["\u254d", "-"], // box drawings heavy double dash horizontal (╍)
  ["\u254e", "|"], // box drawings light double dash vertical (╎)
  ["\u254f", "|"], // box drawings heavy double dash vertical (╏)
  ["\u2550", "-"], // box drawings double horizontal (═)
  ["\u2551", "|"], // box drawings double vertical (║)
  ["\u2552", "+"], // box drawings down single and right double (╒)
  ["\u2553", "+"], // box drawings down double and right single (╓)
  ["\u2554", "+"], // box drawings double down and right (╔)
  ["\u2555", "+"], // box drawings down single and left double (╕)
  ["\u2556", "+"], // box drawings down double and left single (╖)
  ["\u2557", "+"], // box drawings double down and left (╗)
  ["\u2558", "+"], // box drawings up single and right double (╘)
  ["\u2559", "+"], // box drawings up double and right single (╙)
  ["\u255a", "+"], // box drawings double up and right (╚)
  ["\u255b", "+"], // box drawings up single and left double (╛)
  ["\u255c", "+"], // box drawings up double and left single (╜)
  ["\u255d", "+"], // box drawings double up and left (╝)
  ["\u255e", "+"], // box drawings vertical single and right double (╞)
  ["\u255f", "+"], // box drawings vertical double and right single (╟)
  ["\u2560", "+"], // box drawings double vertical and right (╠)
  ["\u2561", "+"], // box drawings vertical single and left double (╡)
  ["\u2562", "+"], // box drawings vertical double and left single (╢)
  ["\u2563", "+"], // box drawings double vertical and left (╣)
  ["\u2564", "+"], // box drawings down single and horizontal double (╤)
  ["\u2565", "+"], // box drawings down double and horizontal single (╥)
  ["\u2566", "+"], // box drawings double down and horizontal (╦)
  ["\u2567", "+"], // box drawings up single and horizontal double (╧)
  ["\u2568", "+"], // box drawings up double and horizontal single (╨)
  ["\u2569", "+"], // box drawings double up and horizontal (╩)
  ["\u256a", "+"], // box drawings vertical single and horizontal double (╪)
  ["\u256b", "+"], // box drawings vertical double and horizontal single (╫)
  ["\u256c", "+"], // box drawings double vertical and horizontal (╬)
  ["\u256d", "+"], // box drawings light arc down and right (╭)
  ["\u256e", "+"], // box drawings light arc down and left (╮)
  ["\u256f", "+"], // box drawings light arc up and left (╯)
  ["\u2570", "+"], // box drawings light arc up and right (╰)
  ["\u2571", "/"], // box drawings light diagonal upper right to lower left (╱)
  ["\u2572", "\\"], // box drawings light diagonal upper left to lower right (╲)
  ["\u2573", "X"], // box drawings light diagonal cross (╳)
  ["\u2574", "-"], // box drawings light left (╴)
  ["\u2575", "|"], // box drawings light up (╵)
  ["\u2576", "-"], // box drawings light right (╶)
  ["\u2577", "|"], // box drawings light down (╷)
  ["\u2578", "-"], // box drawings heavy left (╸)
  ["\u2579", "|"], // box drawings heavy up (╹)
  ["\u257a", "-"], // box drawings heavy right (╺)
  ["\u257b", "|"], // box drawings heavy down (╻)
  ["\u257c", "-"], // box drawings light left and heavy right (╼)
  ["\u257d", "|"], // box drawings light up and heavy down (╽)
  ["\u257e", "-"], // box drawings heavy left and light right (╾)
  ["\u257f", "|"], // box drawings heavy up and light down (╿)
];

export const SHAPES: Array<[string, string]> = [
  // Geometric shapes — the filled/hollow pairs first, then the rest of the
  // block per AnyAscii 0.3.3 in the wholesale section below. The up/down
  // triangles used directionally stay in ARROWS.
  ["\u25CF", "*"], // black circle (●)
  ["\u25CB", "*"], // white circle (○)
  ["\u25A0", "#"], // black square (■)
  ["\u25A1", "#"], // white square (□)
  // ⬛ ⬜ mapped only to a :shortcode:, so they are dropped, not mapped.
  // AnyAscii wholesale — Geometric Shapes by appearance.
  ["\u25a2", "#"], // white square with rounded corners (▢)
  ["\u25a3", "#"], // white square containing black small square (▣)
  ["\u25a4", "#"], // square with horizontal fill (▤)
  ["\u25a5", "#"], // square with vertical fill (▥)
  ["\u25a6", "#"], // square with orthogonal crosshatch fill (▦)
  ["\u25a7", "#"], // square with upper left to lower right fill (▧)
  ["\u25a8", "#"], // square with upper right to lower left fill (▨)
  ["\u25a9", "#"], // square with diagonal crosshatch fill (▩)
  ["\u25ac", "#"], // black rectangle (▬)
  ["\u25ad", "#"], // white rectangle (▭)
  ["\u25ae", "#"], // black vertical rectangle (▮)
  ["\u25af", "#"], // white vertical rectangle (▯)
  ["\u25b0", "#"], // black parallelogram (▰)
  ["\u25b1", "#"], // white parallelogram (▱)
  ["\u25b5", "^"], // white up-pointing small triangle (▵)
  ["\u25b7", ">"], // white right-pointing triangle (▷)
  ["\u25b8", ">"], // black right-pointing small triangle (▸)
  ["\u25b9", ">"], // white right-pointing small triangle (▹)
  ["\u25bb", ">"], // white right-pointing pointer (▻)
  ["\u25bf", "v"], // white down-pointing small triangle (▿)
  ["\u25c1", "<"], // white left-pointing triangle (◁)
  ["\u25c2", "<"], // black left-pointing small triangle (◂)
  ["\u25c3", "<"], // white left-pointing small triangle (◃)
  ["\u25c4", "<"], // black left-pointing pointer (◄)
  ["\u25c5", "<"], // white left-pointing pointer (◅)
  ["\u25c6", "*"], // black diamond (◆)
  ["\u25c7", "*"], // white diamond (◇)
  ["\u25c8", "*"], // white diamond containing black small diamond (◈)
  ["\u25c9", "*"], // fisheye (◉)
  ["\u25ca", "*"], // lozenge (◊)
  ["\u25cc", "*"], // dotted circle (◌)
  ["\u25cd", "*"], // circle with vertical fill (◍)
  ["\u25ce", "*"], // bullseye (◎)
  ["\u25d0", "*"], // circle with left half black (◐)
  ["\u25d1", "*"], // circle with right half black (◑)
  ["\u25d2", "*"], // circle with lower half black (◒)
  ["\u25d3", "*"], // circle with upper half black (◓)
  ["\u25d4", "*"], // circle with upper right quadrant black (◔)
  ["\u25d5", "*"], // circle with all but upper left quadrant black (◕)
  ["\u25d6", "("], // left half black circle (◖)
  ["\u25d7", ")"], // right half black circle (◗)
  ["\u25d8", "*"], // inverse bullet (◘)
  ["\u25d9", "*"], // inverse white circle (◙)
  ["\u25da", "*"], // upper half inverse white circle (◚)
  ["\u25db", "*"], // lower half inverse white circle (◛)
  ["\u25dc", "*"], // upper left quadrant circular arc (◜)
  ["\u25dd", "*"], // upper right quadrant circular arc (◝)
  ["\u25de", "*"], // lower right quadrant circular arc (◞)
  ["\u25df", "*"], // lower left quadrant circular arc (◟)
  ["\u25e0", "*"], // upper half circle (◠)
  ["\u25e1", "*"], // lower half circle (◡)
  ["\u25e2", "/"], // black lower right triangle (◢)
  ["\u25e3", "\\"], // black lower left triangle (◣)
  ["\u25e4", "/"], // black upper left triangle (◤)
  ["\u25e5", "\\"], // black upper right triangle (◥)
  ["\u25e6", "*"], // white bullet (◦)
  ["\u25e7", "#"], // square with left half black (◧)
  ["\u25e8", "#"], // square with right half black (◨)
  ["\u25e9", "#"], // square with upper left diagonal half black (◩)
  ["\u25ea", "#"], // square with lower right diagonal half black (◪)
  ["\u25eb", "#"], // white square with vertical bisecting line (◫)
  ["\u25ec", "^"], // white up-pointing triangle with dot (◬)
  ["\u25ed", "^"], // up-pointing triangle with left half black (◭)
  ["\u25ee", "^"], // up-pointing triangle with right half black (◮)
  ["\u25ef", "*"], // large circle (◯)
  ["\u25f0", "#"], // white square with upper left quadrant (◰)
  ["\u25f1", "#"], // white square with lower left quadrant (◱)
  ["\u25f2", "#"], // white square with lower right quadrant (◲)
  ["\u25f3", "#"], // white square with upper right quadrant (◳)
  ["\u25f4", "*"], // white circle with upper left quadrant (◴)
  ["\u25f5", "*"], // white circle with lower left quadrant (◵)
  ["\u25f6", "*"], // white circle with lower right quadrant (◶)
  ["\u25f7", "*"], // white circle with upper right quadrant (◷)
  ["\u25f8", "/"], // upper left triangle (◸)
  ["\u25f9", "\\"], // upper right triangle (◹)
  ["\u25fa", "\\"], // lower left triangle (◺)
  ["\u25ff", "/"], // lower right triangle (◿)
];

export const ARROWS: Array<[string, string]> = [
  ["\u2192", ">"], // rightwards arrow (→)
  ["\u2190", "<"], // leftwards arrow (←)
  ["\u2191", "^"], // upwards arrow (↑)
  ["\u2193", "v"], // downwards arrow (↓)
  ["\u21D2", ">"], // rightwards double arrow (⇒)
  ["\u21D0", "<"], // leftwards double arrow (⇐)
  ["\u21D4", "-"], // left right double arrow (⇔)
  // The single-headed twins of ⇔ ↔ above, in both orders. Same relation —
  // only the head count differs, and ASCII has no head count. AnyAscii maps
  // the pair to "=".
  ["\u21C4", "="], // rightwards arrow over leftwards arrow (⇄)
  ["\u21C6", "="], // leftwards arrow over rightwards arrow (⇆)
  // The vertical doubles of ↑ ↓, mirroring how ⇐ ⇒ are the doubles of ← →.
  ["\u21D1", "^"], // upwards double arrow (⇑)
  ["\u21D3", "v"], // downwards double arrow (⇓)
  ["\u21A6", ">"], // rightwards arrow from bar (↦)
  ["\u21A4", "<"], // leftwards arrow from bar (↤)
  ["\u21E8", ">"], // rightwards white arrow (⇨)
  ["\u21E6", "<"], // leftwards white arrow (⇦)
  // Completing the white/pedestal arrows per AnyAscii (^): wholesale maps by
  // appearance, so the "return"/"confirm" affordance is not preserved.
  ["\u21E7", "^"], // upwards white arrow (⇧)
  ["\u21E9", "v"], // downwards white arrow (⇩)
  ["\u2B9E", ">"], // black rightwards arrowhead (⮞) – U+2B9E
  // The black twin of ↔, from the same block as the three arrows above.
  ["\u2B0C", "-"], // left right black arrow (⬌)
  ["\u25BC", "v"], // black down-pointing triangle (▼)
  ["\u25B2", "^"], // black up-pointing triangle (▲)
  // The white and small siblings of ▲ ▼, mapped the same way. The lozenges,
  // half-circles and remaining exotic shapes of U+25AC-U+25EF are mapped by
  // appearance in the SHAPES wholesale section.
  ["\u25BD", "v"], // white down-pointing triangle (▽)
  ["\u25B3", "^"], // white up-pointing triangle (△)
  ["\u25BE", "v"], // black down-pointing small triangle (▾)
  ["\u25B4", "^"], // black up-pointing small triangle (▴)
  // Directional triangles (filled siblings of ▲/▼) and hook arrows.
  ["\u21B5", "<"], // downwards arrow with corner leftwards (↵)
  // Circular arrows: undo and retry.
  ["\u21BA", "<"], // anticlockwise open circle arrow (↺)
  ["\u21BB", ">"], // clockwise open circle arrow (↻)
  // Dashed and heavy round-tipped variants, twins of the arrows above.
  ["\u21E0", "<"], // leftwards dashed arrow (⇠)
  ["\u21E2", ">"], // rightwards dashed arrow (⇢)
  ["\u21E1", "^"], // upwards dashed arrow (⇡)
  ["\u21E3", "v"], // downwards dashed arrow (⇣)
  // And the squiggle arrow, the one remaining rightwards variant whose shape
  // differs but whose direction does not.
  ["\u21DD", ">"], // rightwards squiggle arrow (⇝)
  // The head-style family. ➡ ➤ ➜ are already mapped above and a model picks
  // between ➔ ➝ ➞ ➠ on nothing but which glyph its training data favoured, so
  // all four take ">", the target ➤ ➜ already take.
  ["\u2794", ">"], // heavy wide-headed rightwards arrow (➔)
  ["\u279D", ">"], // triangle-headed rightwards arrow (➝)
  ["\u279E", ">"], // heavy triangle-headed rightwards arrow (➞)
  ["\u27A0", ">"], // heavy dashed triangle-headed rightwards arrow (➠)
  ["\u279C", ">"], // heavy round-tipped rightwards arrow (➜)
  ["\u27A4", ">"], // black rightwards arrowhead (➤)
  // AnyAscii wholesale — Arrows and Miscellaneous Symbols and Arrows.
  // Arrows whose only value is a :shortcode: (↔ ↕ …) are dropped.
  ["\u219a", "<"], // leftwards arrow with stroke (↚)
  ["\u219b", ">"], // rightwards arrow with stroke (↛)
  ["\u219c", "<"], // leftwards wave arrow (↜)
  ["\u219d", ">"], // rightwards wave arrow (↝)
  ["\u219e", "<"], // leftwards two headed arrow (↞)
  ["\u219f", "^"], // upwards two headed arrow (↟)
  ["\u21a0", ">"], // rightwards two headed arrow (↠)
  ["\u21a1", "v"], // downwards two headed arrow (↡)
  ["\u21a2", "<"], // leftwards arrow with tail (↢)
  ["\u21a3", ">"], // rightwards arrow with tail (↣)
  ["\u21a5", "^"], // upwards arrow from bar (↥)
  ["\u21a7", "v"], // downwards arrow from bar (↧)
  ["\u21a8", "|"], // up down arrow with base (↨)
  ["\u21ab", "<"], // leftwards arrow with loop (↫)
  ["\u21ac", ">"], // rightwards arrow with loop (↬)
  ["\u21ad", "~"], // left right wave arrow (↭)
  ["\u21ae", "-"], // left right arrow with stroke (↮)
  ["\u21af", "v"], // downwards zigzag arrow (↯)
  ["\u21b0", "<"], // upwards arrow with tip leftwards (↰)
  ["\u21b1", ">"], // upwards arrow with tip rightwards (↱)
  ["\u21b2", "<"], // downwards arrow with tip leftwards (↲)
  ["\u21b3", ">"], // downwards arrow with tip rightwards (↳)
  ["\u21b4", "v"], // rightwards arrow with corner downwards (↴)
  ["\u21b6", "<"], // anticlockwise top semicircle arrow (↶)
  ["\u21b7", ">"], // clockwise top semicircle arrow (↷)
  ["\u21b8", "\\"], // north west arrow to long bar (↸)
  ["\u21b9", "="], // leftwards arrow to bar over rightwards arrow to bar (↹)
  ["\u21bc", "<"], // leftwards harpoon with barb upwards (↼)
  ["\u21bd", "<"], // leftwards harpoon with barb downwards (↽)
  ["\u21be", "^"], // upwards harpoon with barb rightwards (↾)
  ["\u21bf", "^"], // upwards harpoon with barb leftwards (↿)
  ["\u21c0", ">"], // rightwards harpoon with barb upwards (⇀)
  ["\u21c1", ">"], // rightwards harpoon with barb downwards (⇁)
  ["\u21c2", "v"], // downwards harpoon with barb rightwards (⇂)
  ["\u21c3", "v"], // downwards harpoon with barb leftwards (⇃)
  ["\u21c5", "|"], // upwards arrow leftwards of downwards arrow (⇅)
  ["\u21c7", "<"], // leftwards paired arrows (⇇)
  ["\u21c8", "^"], // upwards paired arrows (⇈)
  ["\u21c9", ">"], // rightwards paired arrows (⇉)
  ["\u21ca", "v"], // downwards paired arrows (⇊)
  ["\u21cb", "="], // leftwards harpoon over rightwards harpoon (⇋)
  ["\u21cc", "="], // rightwards harpoon over leftwards harpoon (⇌)
  ["\u21cd", "<"], // leftwards double arrow with stroke (⇍)
  ["\u21ce", "-"], // left right double arrow with stroke (⇎)
  ["\u21cf", ">"], // rightwards double arrow with stroke (⇏)
  ["\u21d5", "|"], // up down double arrow (⇕)
  ["\u21d6", "\\"], // north west double arrow (⇖)
  ["\u21d7", "/"], // north east double arrow (⇗)
  ["\u21d8", "\\"], // south east double arrow (⇘)
  ["\u21d9", "/"], // south west double arrow (⇙)
  ["\u21da", "<"], // leftwards triple arrow (⇚)
  ["\u21db", ">"], // rightwards triple arrow (⇛)
  ["\u21dc", "<"], // leftwards squiggle arrow (⇜)
  ["\u21de", "^"], // upwards arrow with double stroke (⇞)
  ["\u21df", "v"], // downwards arrow with double stroke (⇟)
  ["\u21e4", "<"], // leftwards arrow to bar (⇤)
  ["\u21e5", ">"], // rightwards arrow to bar (⇥)
  ["\u21ea", "^"], // upwards white arrow from bar (⇪)
  ["\u21eb", "^"], // upwards white arrow on pedestal (⇫)
  ["\u21ec", "^"], // upwards white arrow on pedestal with horizontal bar (⇬)
  ["\u21ed", "^"], // upwards white arrow on pedestal with vertical bar (⇭)
  ["\u21ee", "^"], // upwards white double arrow (⇮)
  ["\u21ef", "^"], // upwards white double arrow on pedestal (⇯)
  ["\u21f0", ">"], // rightwards white arrow from wall (⇰)
  ["\u21f1", "\\"], // north west arrow to corner (⇱)
  ["\u21f2", "\\"], // south east arrow to corner (⇲)
  ["\u21f3", "|"], // up down white arrow (⇳)
  ["\u21f4", ">"], // right arrow with small circle (⇴)
  ["\u21f5", "|"], // downwards arrow leftwards of upwards arrow (⇵)
  ["\u21f6", ">"], // three rightwards arrows (⇶)
  ["\u21f7", "<"], // leftwards arrow with vertical stroke (⇷)
  ["\u21f8", ">"], // rightwards arrow with vertical stroke (⇸)
  ["\u21f9", "-"], // left right arrow with vertical stroke (⇹)
  ["\u21fa", "<"], // leftwards arrow with double vertical stroke (⇺)
  ["\u21fb", ">"], // rightwards arrow with double vertical stroke (⇻)
  ["\u21fc", "-"], // left right arrow with double vertical stroke (⇼)
  ["\u21fd", "<"], // leftwards open-headed arrow (⇽)
  ["\u21fe", ">"], // rightwards open-headed arrow (⇾)
  ["\u21ff", "-"], // left right open-headed arrow (⇿)
  ["\u2b00", "/"], // north east white arrow (⬀)
  ["\u2b01", "\\"], // north west white arrow (⬁)
  ["\u2b02", "\\"], // south east white arrow (⬂)
  ["\u2b03", "/"], // south west white arrow (⬃)
  ["\u2b04", "-"], // left right white arrow (⬄)
  ["\u2b08", "/"], // north east black arrow (⬈)
  ["\u2b09", "\\"], // north west black arrow (⬉)
  ["\u2b0a", "\\"], // south east black arrow (⬊)
  ["\u2b0b", "/"], // south west black arrow (⬋)
  ["\u2b0d", "|"], // up down black arrow (⬍)
  ["\u2b0e", "v"], // rightwards arrow with tip downwards (⬎)
  ["\u2b0f", "^"], // rightwards arrow with tip upwards (⬏)
  ["\u2b10", "v"], // leftwards arrow with tip downwards (⬐)
  ["\u2b11", "^"], // leftwards arrow with tip upwards (⬑)
  ["\u2b12", "-"], // square with top half black (⬒)
  ["\u2b13", "-"], // square with bottom half black (⬓)
  ["\u2b14", "\\"], // square with upper right diagonal half black (⬔)
  ["\u2b15", "\\"], // square with lower left diagonal half black (⬕)
  ["\u2b16", "|"], // diamond with left half black (⬖)
  ["\u2b17", "|"], // diamond with right half black (⬗)
  ["\u2b18", "-"], // diamond with top half black (⬘)
  ["\u2b19", "-"], // diamond with bottom half black (⬙)
  ["\u2b1a", "#"], // dotted square (⬚)
  ["\u2b1d", "-"], // black very small square (⬝)
  ["\u2b1e", "-"], // white very small square (⬞)
  ["\u2b1f", "*"], // black pentagon (⬟)
  ["\u2b20", "*"], // white pentagon (⬠)
  ["\u2b21", "*"], // white hexagon (⬡)
  ["\u2b22", "*"], // black hexagon (⬢)
  ["\u2b23", "*"], // horizontal black hexagon (⬣)
  ["\u2b24", "*"], // black large circle (⬤)
  ["\u2b25", "*"], // black medium diamond (⬥)
  ["\u2b26", "*"], // white medium diamond (⬦)
  ["\u2b27", "*"], // black medium lozenge (⬧)
  ["\u2b28", "*"], // white medium lozenge (⬨)
  ["\u2b29", "*"], // black small diamond (⬩)
  ["\u2b2a", "*"], // black small lozenge (⬪)
  ["\u2b2b", "*"], // white small lozenge (⬫)
  ["\u2b2c", "*"], // black horizontal ellipse (⬬)
  ["\u2b2d", "*"], // white horizontal ellipse (⬭)
  ["\u2b2e", "*"], // black vertical ellipse (⬮)
  ["\u2b2f", "*"], // white vertical ellipse (⬯)
  ["\u2b30", "<"], // left arrow with small circle (⬰)
  ["\u2b31", "<"], // three leftwards arrows (⬱)
  ["\u2b32", "<"], // left arrow with circled plus (⬲)
  ["\u2b33", "<"], // long leftwards squiggle arrow (⬳)
  ["\u2b34", "<"], // leftwards two-headed arrow with vertical stroke (⬴)
  ["\u2b35", "<"], // leftwards two-headed arrow with double vertical stroke (⬵)
  ["\u2b36", "<"], // leftwards two-headed arrow from bar (⬶)
  ["\u2b37", "<"], // leftwards two-headed triple dash arrow (⬷)
  ["\u2b38", "<"], // leftwards arrow with dotted stem (⬸)
  ["\u2b39", "<"], // leftwards arrow with tail with vertical stroke (⬹)
  ["\u2b3a", "<"], // leftwards arrow with tail with double vertical stroke (⬺)
  ["\u2b3b", "<"], // leftwards two-headed arrow with tail (⬻)
  ["\u2b3c", "<"], // leftwards two-headed arrow with tail with vertical stroke (⬼)
  ["\u2b3d", "<"], // leftwards two-headed arrow with tail with double vertical stroke (⬽)
  ["\u2b3e", "<"], // leftwards arrow through x (⬾)
  ["\u2b3f", "<"], // wave arrow pointing directly left (⬿)
  ["\u2b40", "<"], // equals sign above leftwards arrow (⭀)
  ["\u2b41", "<"], // reverse tilde operator above leftwards arrow (⭁)
  ["\u2b42", "<"], // leftwards arrow above reverse almost equal to (⭂)
  ["\u2b43", ">"], // rightwards arrow through greater-than (⭃)
  ["\u2b44", ">"], // rightwards arrow through superset (⭄)
  ["\u2b45", "<"], // leftwards quadruple arrow (⭅)
  ["\u2b46", ">"], // rightwards quadruple arrow (⭆)
  ["\u2b47", ">"], // reverse tilde operator above rightwards arrow (⭇)
  ["\u2b48", ">"], // rightwards arrow above reverse almost equal to (⭈)
  ["\u2b49", "<"], // tilde operator above leftwards arrow (⭉)
  ["\u2b4a", "<"], // leftwards arrow above almost equal to (⭊)
  ["\u2b4b", "<"], // leftwards arrow above reverse tilde operator (⭋)
  ["\u2b4c", ">"], // rightwards arrow above reverse tilde operator (⭌)
  ["\u2b4d", "v"], // downwards triangle-headed zigzag arrow (⭍)
  ["\u2b4e", "/"], // short slanted north arrow (⭎)
  ["\u2b4f", "\\"], // short backslanted south arrow (⭏)
  ["\u2b51", "*"], // black small star (⭑)
  ["\u2b52", "*"], // white small star (⭒)
  ["\u2b53", "*"], // black right-pointing pentagon (⭓)
  ["\u2b54", "*"], // white right-pointing pentagon (⭔)
  ["\u2b56", "*"], // heavy oval with oval inside (⭖)
  ["\u2b57", "*"], // heavy circle with circle inside (⭗)
  ["\u2b58", "*"], // heavy circle (⭘)
  ["\u2b59", "*"], // heavy circled saltire (⭙)
  ["\u2b5a", "/"], // slanted north arrow with hooked head (⭚)
  ["\u2b5b", "\\"], // backslanted south arrow with hooked tail (⭛)
  ["\u2b5c", "/"], // slanted north arrow with horizontal tail (⭜)
  ["\u2b5d", "\\"], // backslanted south arrow with horizontal tail (⭝)
  ["\u2b5e", ">"], // bent arrow pointing downwards then north east (⭞)
  ["\u2b5f", ">"], // short bent arrow pointing downwards then north east (⭟)
  ["\u2b60", "<"], // leftwards triangle-headed arrow (⭠)
  ["\u2b61", "^"], // upwards triangle-headed arrow (⭡)
  ["\u2b62", ">"], // rightwards triangle-headed arrow (⭢)
  ["\u2b63", "v"], // downwards triangle-headed arrow (⭣)
  ["\u2b64", "-"], // left right triangle-headed arrow (⭤)
  ["\u2b65", "|"], // up down triangle-headed arrow (⭥)
  ["\u2b66", "\\"], // north west triangle-headed arrow (⭦)
  ["\u2b67", "/"], // north east triangle-headed arrow (⭧)
  ["\u2b68", "\\"], // south east triangle-headed arrow (⭨)
  ["\u2b69", "/"], // south west triangle-headed arrow (⭩)
  ["\u2b6a", "<"], // leftwards triangle-headed dashed arrow (⭪)
  ["\u2b6b", "^"], // upwards triangle-headed dashed arrow (⭫)
  ["\u2b6c", ">"], // rightwards triangle-headed dashed arrow (⭬)
  ["\u2b6d", "v"], // downwards triangle-headed dashed arrow (⭭)
  ["\u2b6e", ">"], // clockwise triangle-headed open circle arrow (⭮)
  ["\u2b6f", "<"], // anticlockwise triangle-headed open circle arrow (⭯)
  ["\u2b70", "<"], // leftwards triangle-headed arrow to bar (⭰)
  ["\u2b71", "^"], // upwards triangle-headed arrow to bar (⭱)
  ["\u2b72", ">"], // rightwards triangle-headed arrow to bar (⭲)
  ["\u2b73", "v"], // downwards triangle-headed arrow to bar (⭳)
  ["\u2b76", "\\"], // north west triangle-headed arrow to bar (⭶)
  ["\u2b77", "/"], // north east triangle-headed arrow to bar (⭷)
  ["\u2b78", "\\"], // south east triangle-headed arrow to bar (⭸)
  ["\u2b79", "/"], // south west triangle-headed arrow to bar (⭹)
  ["\u2b7a", "<"], // leftwards triangle-headed arrow with double horizontal stroke (⭺)
  ["\u2b7b", "^"], // upwards triangle-headed arrow with double horizontal stroke (⭻)
  ["\u2b7c", ">"], // rightwards triangle-headed arrow with double horizontal stroke (⭼)
  ["\u2b7d", "v"], // downwards triangle-headed arrow with double horizontal stroke (⭽)
  ["\u2b7e", "="], // horizontal tab key (⭾)
  ["\u2b7f", "|"], // vertical tab key (⭿)
  ["\u2b80", "="], // leftwards triangle-headed arrow over rightwards triangle-headed arrow (⮀)
  ["\u2b81", "|"], // upwards triangle-headed arrow leftwards of downwards triangle-headed arrow (⮁)
  ["\u2b82", "="], // rightwards triangle-headed arrow over leftwards triangle-headed arrow (⮂)
  ["\u2b83", "|"], // downwards triangle-headed arrow leftwards of upwards triangle-headed arrow (⮃)
  ["\u2b84", "<"], // leftwards triangle-headed paired arrows (⮄)
  ["\u2b85", "^"], // upwards triangle-headed paired arrows (⮅)
  ["\u2b86", ">"], // rightwards triangle-headed paired arrows (⮆)
  ["\u2b87", "v"], // downwards triangle-headed paired arrows (⮇)
  ["\u2b88", "<"], // leftwards black circled white arrow (⮈)
  ["\u2b89", "^"], // upwards black circled white arrow (⮉)
  ["\u2b8a", ">"], // rightwards black circled white arrow (⮊)
  ["\u2b8b", "v"], // downwards black circled white arrow (⮋)
  ["\u2b8c", "<"], // anticlockwise triangle-headed right u-shaped arrow (⮌)
  ["\u2b8d", "^"], // anticlockwise triangle-headed bottom u-shaped arrow (⮍)
  ["\u2b8e", ">"], // anticlockwise triangle-headed left u-shaped arrow (⮎)
  ["\u2b8f", "v"], // anticlockwise triangle-headed top u-shaped arrow (⮏)
  ["\u2b90", "<"], // return left (⮐)
  ["\u2b91", ">"], // return right (⮑)
  ["\u2b92", "<"], // newline left (⮒)
  ["\u2b93", ">"], // newline right (⮓)
  ["\u2b94", "*"], // four corner arrows circling anticlockwise (⮔)
  ["\u2b95", ">"], // rightwards black arrow (⮕)
  ["\u2b97", "A"], // symbol for type a electronics (⮗)
  ["\u2b98", "<"], // three-d top-lighted leftwards equilateral arrowhead (⮘)
  ["\u2b99", "^"], // three-d right-lighted upwards equilateral arrowhead (⮙)
  ["\u2b9a", ">"], // three-d top-lighted rightwards equilateral arrowhead (⮚)
  ["\u2b9b", "v"], // three-d left-lighted downwards equilateral arrowhead (⮛)
  ["\u2b9c", "<"], // black leftwards equilateral arrowhead (⮜)
  ["\u2b9d", "^"], // black upwards equilateral arrowhead (⮝)
  ["\u2b9f", "v"], // black downwards equilateral arrowhead (⮟)
  ["\u2ba0", "<"], // downwards triangle-headed arrow with long tip leftwards (⮠)
  ["\u2ba1", ">"], // downwards triangle-headed arrow with long tip rightwards (⮡)
  ["\u2ba2", "<"], // upwards triangle-headed arrow with long tip leftwards (⮢)
  ["\u2ba3", ">"], // upwards triangle-headed arrow with long tip rightwards (⮣)
  ["\u2ba4", "^"], // leftwards triangle-headed arrow with long tip upwards (⮤)
  ["\u2ba5", "^"], // rightwards triangle-headed arrow with long tip upwards (⮥)
  ["\u2ba6", "v"], // leftwards triangle-headed arrow with long tip downwards (⮦)
  ["\u2ba7", "v"], // rightwards triangle-headed arrow with long tip downwards (⮧)
  ["\u2ba8", "<"], // black curved downwards and leftwards arrow (⮨)
  ["\u2ba9", ">"], // black curved downwards and rightwards arrow (⮩)
  ["\u2baa", "<"], // black curved upwards and leftwards arrow (⮪)
  ["\u2bab", ">"], // black curved upwards and rightwards arrow (⮫)
  ["\u2bac", "^"], // black curved leftwards and upwards arrow (⮬)
  ["\u2bad", "^"], // black curved rightwards and upwards arrow (⮭)
  ["\u2bae", "v"], // black curved leftwards and downwards arrow (⮮)
  ["\u2baf", "v"], // black curved rightwards and downwards arrow (⮯)
  ["\u2bb0", "<"], // ribbon arrow down left (⮰)
  ["\u2bb1", ">"], // ribbon arrow down right (⮱)
  ["\u2bb2", "<"], // ribbon arrow up left (⮲)
  ["\u2bb3", ">"], // ribbon arrow up right (⮳)
  ["\u2bb4", "^"], // ribbon arrow left up (⮴)
  ["\u2bb5", "^"], // ribbon arrow right up (⮵)
  ["\u2bb6", "v"], // ribbon arrow left down (⮶)
  ["\u2bb7", "v"], // ribbon arrow right down (⮷)
  ["\u2bb8", "^"], // upwards white arrow from bar with horizontal bar (⮸)
  ["\u2bb9", "^"], // up arrowhead in a rectangle box (⮹)
  ["\u2bba", "*"], // overlapping white squares (⮺)
  ["\u2bbb", "*"], // overlapping white and black squares (⮻)
  ["\u2bbc", "*"], // overlapping black squares (⮼)
  ["\u2bbd", "x"], // ballot box with light x (⮽)
  ["\u2bbe", "x"], // circled x (⮾)
  ["\u2bbf", "x"], // circled bold x (⮿)
  ["\u2bc0", "*"], // black square centred (⯀)
  ["\u2bc1", "*"], // black diamond centred (⯁)
  ["\u2bc2", "*"], // turned black pentagon (⯂)
  ["\u2bc3", "*"], // horizontal black octagon (⯃)
  ["\u2bc4", "*"], // black octagon (⯄)
  ["\u2bc5", "^"], // black medium up-pointing triangle centred (⯅)
  ["\u2bc6", "v"], // black medium down-pointing triangle centred (⯆)
  ["\u2bc7", "<"], // black medium left-pointing triangle centred (⯇)
  ["\u2bc8", ">"], // black medium right-pointing triangle centred (⯈)
  ["\u2bc9", "Neptune"], // neptune form two (⯉)
  ["\u2bca", "^"], // top half black circle (⯊)
  ["\u2bcb", "v"], // bottom half black circle (⯋)
  ["\u2bcc", "*"], // light four pointed black cusp (⯌)
  ["\u2bcd", "*"], // rotated light four pointed black cusp (⯍)
  ["\u2bce", "*"], // white four pointed cusp (⯎)
  ["\u2bcf", "*"], // rotated white four pointed cusp (⯏)
  ["\u2bd0", "+"], // square position indicator (⯐)
  ["\u2bd1", "?"], // uncertainty sign (⯑)
  ["\u2bd2", "+"], // group mark (⯒)
  ["\u2bd3", "Pluto"], // pluto form two (⯓)
  ["\u2bd4", "Pluto"], // pluto form three (⯔)
  ["\u2bd5", "Pluto"], // pluto form four (⯕)
  ["\u2bd6", "Pluto"], // pluto form five (⯖)
  ["\u2bd7", "*"], // transpluto (⯗)
  ["\u2bd8", "*"], // proserpina (⯘)
  ["\u2bd9", "*"], // astraea (⯙)
  ["\u2bda", "*"], // hygiea (⯚)
  ["\u2bdb", "*"], // pholus (⯛)
  ["\u2bdc", "*"], // nessus (⯜)
  ["\u2bdd", "*"], // white moon selena (⯝)
  ["\u2bde", "*"], // black diamond on cross (⯞)
  ["\u2bdf", "*"], // true light moon arta (⯟)
  ["\u2be0", "Cupido"], // cupido (⯠)
  ["\u2be1", "Hades"], // hades (⯡)
  ["\u2be2", "Zeus"], // zeus (⯢)
  ["\u2be3", "Kronos"], // kronos (⯣)
  ["\u2be4", "Apollon"], // apollon (⯤)
  ["\u2be5", "Admetos"], // admetos (⯥)
  ["\u2be6", "Vulcanus"], // vulcanus (⯦)
  ["\u2be7", "Poseidon"], // poseidon (⯧)
  ["\u2be8", "*"], // left half black star (⯨)
  ["\u2be9", "*"], // right half black star (⯩)
  ["\u2bea", "*"], // star with left half black (⯪)
  ["\u2beb", "*"], // star with right half black (⯫)
  ["\u2bec", "<"], // leftwards two-headed arrow with triangle arrowheads (⯬)
  ["\u2bed", "^"], // upwards two-headed arrow with triangle arrowheads (⯭)
  ["\u2bee", ">"], // rightwards two-headed arrow with triangle arrowheads (⯮)
  ["\u2bef", "v"], // downwards two-headed arrow with triangle arrowheads (⯯)
  ["\u2bf0", "*"], // eris form one (⯰)
  ["\u2bf1", "*"], // eris form two (⯱)
  ["\u2bf2", "*"], // sedna (⯲)
  ["\u2bf3", "V"], // russian astrological symbol vigintile (⯳)
  ["\u2bf4", "N"], // russian astrological symbol novile (⯴)
  ["\u2bf5", "Q"], // russian astrological symbol quintile (⯵)
  ["\u2bf6", "N2"], // russian astrological symbol binovile (⯶)
  ["\u2bf7", "100"], // russian astrological symbol sentagon (⯷)
  ["\u2bf8", "D3"], // russian astrological symbol tredecile (⯸)
  ["\u2bf9", "*"], // equals sign with infinity below (⯹)
  ["\u2bfa", "*"], // united symbol (⯺)
  ["\u2bfb", "*"], // separated symbol (⯻)
  ["\u2bfc", "*"], // doubled symbol (⯼)
  ["\u2bfd", "*"], // passed symbol (⯽)
  ["\u2bfe", "*"], // reversed right angle (⯾)
  ["\u2bff", "#"], // hellschreiber pause symbol (⯿)
];

export const MATH: Array<[string, string]> = [
  // Equality and ordering. Each non-strict relation has a strict twin further
  // down (≠ below, ⊂/⊃ below), so the two families are kept together: mapping
  // ⊂ but not ⊆ left "set ⊆ {1}" with the subset silently dropped.
  ["\u2260", "="], // not equal to (≠)
  ["\u2261", "="], // identical to (≡)
  ["\u2264", "<="], // less-than or equal to (≤)
  ["\u2265", ">="], // greater-than or equal to (≥)
  // Stacked relations and the parallel sign, siblings of ≪ ≫.
  ["\u2266", "<="], // less-than over equal to (≦)
  ["\u2267", ">="], // greater-than over equal to (≧)
  ["\u2225", "||"], // parallel to (∥)
  ["\u226A", "<<"], // much less-than (≪)
  ["\u226B", ">>"], // much greater-than (≫)
  ["\u00D7", "*"], // multiplication sign (×)
  ["\u00F7", "/"], // division sign (÷)
  ["\u00B1", "+-"], // plus-minus sign (±)
  ["\u2212", "-"], // minus sign (−)
  ["\u221E", "inf"], // infinity (∞)
  ["\u2248", "~"], // almost equal to (≈)
  ["\u223C", "~"], // tilde operator (∼)
  ["\u221A", "sqrt"], // square root (√)
  ["\u2211", "S"], // n-ary summation (∑)
  ["\u220F", "P"], // n-ary product (∏)
  ["\u2202", "d"], // partial differential (∂)
  ["\u2207", "D"], // nabla (∇)
  ["\u2208", "E"], // element of (∈)
  ["\u2209", "E"], // not an element of (∉)
  ["\u2229", "^"], // intersection (∩)
  ["\u222A", "v"], // union (∪)
  ["\u2282", "<"], // subset of (⊂)
  ["\u2283", ">"], // superset of (⊃)
  ["\u2286", "<"], // subset of or equal to (⊆)
  ["\u2287", ">"], // superset of or equal to (⊇)
  ["\u2227", "^"], // logical and (∧)
  ["\u2228", "v"], // logical or (∨)
  ["\u00AC", "!"], // not sign (¬)
  ["\u2234", ":"], // therefore (∴)
  ["\u2235", ":"], // because (∵)
  // Quantifiers and the empty set, which appear constantly in algorithm and
  // complexity discussions.
  ["\u2200", "V"], // for all (∀)
  ["\u2205", "0"], // empty set (∅)
  // Dotted operators per AnyAscii 0.3.3. The middle dot and ellipsis in
  // PUNCTUATION map their own way.
  ["\u22C5", "*"], // dot operator (⋅)
  ["\u22EF", "-"], // midline horizontal ellipsis (⋯)
  // AnyAscii wholesale — Mathematical Operators.
  ["\u2201", "C"], // complement (∁)
  ["\u2203", "E"], // there exists (∃)
  ["\u2204", "E"], // there does not exist (∄)
  ["\u2206", "^"], // increment (∆)
  ["\u220a", "E"], // small element of (∊)
  ["\u220b", "E"], // contains as member (∋)
  ["\u220c", "E"], // does not contain as member (∌)
  ["\u220d", "E"], // small contains as member (∍)
  ["\u220e", "#"], // end of proof (∎)
  ["\u2210", "U"], // n-ary coproduct (∐)
  ["\u2213", "-+"], // minus-or-plus sign (∓)
  ["\u2214", "+"], // dot plus (∔)
  ["\u2215", "/"], // division slash (∕)
  ["\u2216", "\\"], // set minus (∖)
  ["\u2217", "*"], // asterisk operator (∗)
  ["\u2218", "*"], // ring operator (∘)
  ["\u2219", "*"], // bullet operator (∙)
  ["\u221b", "cbrt"], // cube root (∛)
  ["\u221c", "4rt"], // fourth root (∜)
  ["\u221d", "~"], // proportional to (∝)
  ["\u221f", "L"], // right angle (∟)
  ["\u2220", "<"], // angle (∠)
  ["\u2221", "<"], // measured angle (∡)
  ["\u2222", "<"], // spherical angle (∢)
  ["\u2223", "|"], // divides (∣)
  ["\u2224", "|"], // does not divide (∤)
  ["\u2226", "||"], // not parallel to (∦)
  ["\u222b", "S"], // integral (∫)
  ["\u222c", "S"], // double integral (∬)
  ["\u222d", "SSS"], // triple integral (∭)
  ["\u222e", "S"], // contour integral (∮)
  ["\u222f", "SS"], // surface integral (∯)
  ["\u2230", "SSS"], // volume integral (∰)
  ["\u2231", "S"], // clockwise integral (∱)
  ["\u2232", "S"], // clockwise contour integral (∲)
  ["\u2233", "S"], // anticlockwise contour integral (∳)
  ["\u2236", ":"], // ratio (∶)
  ["\u2237", "::"], // proportion (∷)
  ["\u2238", "_"], // dot minus (∸)
  ["\u2239", "-:"], // excess (∹)
  ["\u223a", "-"], // geometric proportion (∺)
  ["\u223b", "~"], // homothetic (∻)
  ["\u223d", "~"], // reversed tilde (∽)
  ["\u223e", "~"], // inverted lazy s (∾)
  ["\u223f", "~"], // sine wave (∿)
  ["\u2240", "~"], // wreath product (≀)
  ["\u2241", "~"], // not tilde (≁)
  ["\u2242", "-~"], // minus tilde (≂)
  ["\u2243", "~"], // asymptotically equal to (≃)
  ["\u2244", "~"], // not asymptotically equal to (≄)
  ["\u2245", "~="], // approximately equal to (≅)
  ["\u2246", "="], // approximately but not actually equal to (≆)
  ["\u2247", "="], // neither approximately nor actually equal to (≇)
  ["\u2249", "~"], // not almost equal to (≉)
  ["\u224a", "~"], // almost equal or equal to (≊)
  ["\u224b", "~"], // triple tilde (≋)
  ["\u224c", "~="], // all equal to (≌)
  ["\u224d", "="], // equivalent to (≍)
  ["\u224e", "="], // geometrically equivalent to (≎)
  ["\u224f", "="], // difference between (≏)
  ["\u2250", "="], // approaches the limit (≐)
  ["\u2251", "="], // geometrically equal to (≑)
  ["\u2252", "="], // approximately equal to or the image of (≒)
  ["\u2253", "="], // image of or approximately equal to (≓)
  ["\u2254", ":="], // colon equals (≔)
  ["\u2255", "=:"], // equals colon (≕)
  ["\u2256", "="], // ring in equal to (≖)
  ["\u2257", "="], // ring equal to (≗)
  ["\u2258", "="], // corresponds to (≘)
  ["\u2259", "="], // estimates (≙)
  ["\u225a", "="], // equiangular to (≚)
  ["\u225b", "="], // star equals (≛)
  ["\u225c", "="], // delta equal to (≜)
  ["\u225d", "="], // equal to by definition (≝)
  ["\u225e", "="], // measured by (≞)
  ["\u225f", "="], // questioned equal to (≟)
  ["\u2262", "="], // not identical to (≢)
  ["\u2263", "="], // strictly equivalent to (≣)
  ["\u2268", "<"], // less-than but not equal to (≨)
  ["\u2269", ">"], // greater-than but not equal to (≩)
  ["\u226c", "()"], // between (≬)
  ["\u226d", "="], // not equivalent to (≭)
  ["\u226e", "<"], // not less-than (≮)
  ["\u226f", ">"], // not greater-than (≯)
  ["\u2270", "<"], // neither less-than nor equal to (≰)
  ["\u2271", ">"], // neither greater-than nor equal to (≱)
  ["\u2272", "<~"], // less-than or equivalent to (≲)
  ["\u2273", ">~"], // greater-than or equivalent to (≳)
  ["\u2274", "<"], // neither less-than nor equivalent to (≴)
  ["\u2275", ">"], // neither greater-than nor equivalent to (≵)
  ["\u2276", "="], // less-than or greater-than (≶)
  ["\u2277", "="], // greater-than or less-than (≷)
  ["\u2278", "="], // neither less-than nor greater-than (≸)
  ["\u2279", "="], // neither greater-than nor less-than (≹)
  ["\u227a", "<"], // precedes (≺)
  ["\u227b", ">"], // succeeds (≻)
  ["\u227c", "<"], // precedes or equal to (≼)
  ["\u227d", ">"], // succeeds or equal to (≽)
  ["\u227e", "<"], // precedes or equivalent to (≾)
  ["\u227f", ">"], // succeeds or equivalent to (≿)
  ["\u2280", "<"], // does not precede (⊀)
  ["\u2281", ">"], // does not succeed (⊁)
  ["\u2284", "<"], // not a subset of (⊄)
  ["\u2285", ">"], // not a superset of (⊅)
  ["\u2288", "<"], // neither a subset of nor equal to (⊈)
  ["\u2289", ">"], // neither a superset of nor equal to (⊉)
  ["\u228a", "<"], // subset of with not equal to (⊊)
  ["\u228b", ">"], // superset of with not equal to (⊋)
  ["\u228c", "v"], // multiset (⊌)
  ["\u228d", "v"], // multiset multiplication (⊍)
  ["\u228e", "v"], // multiset union (⊎)
  ["\u228f", "["], // square image of (⊏)
  ["\u2290", "]"], // square original of (⊐)
  ["\u2291", "["], // square image of or equal to (⊑)
  ["\u2292", "]"], // square original of or equal to (⊒)
  ["\u2293", "^"], // square cap (⊓)
  ["\u2294", "v"], // square cup (⊔)
  ["\u2295", "+"], // circled plus (⊕)
  ["\u2296", "-"], // circled minus (⊖)
  ["\u2297", "x"], // circled times (⊗)
  ["\u2298", "/"], // circled division slash (⊘)
  ["\u2299", "."], // circled dot operator (⊙)
  ["\u229a", "o"], // circled ring operator (⊚)
  ["\u229b", "*"], // circled asterisk operator (⊛)
  ["\u229c", "="], // circled equals (⊜)
  ["\u229d", "-"], // circled dash (⊝)
  ["\u229e", "+"], // squared plus (⊞)
  ["\u229f", "-"], // squared minus (⊟)
  ["\u22a0", "x"], // squared times (⊠)
  ["\u22a1", "."], // squared dot operator (⊡)
  ["\u22a2", "+"], // right tack (⊢)
  ["\u22a3", "+"], // left tack (⊣)
  ["\u22a4", "+"], // down tack (⊤)
  ["\u22a5", "+"], // up tack (⊥)
  ["\u22a6", "+"], // assertion (⊦)
  ["\u22a7", "+"], // models (⊧)
  ["\u22a8", "+"], // true (⊨)
  ["\u22a9", "+"], // forces (⊩)
  ["\u22aa", "+"], // triple vertical bar right turnstile (⊪)
  ["\u22ab", "+"], // double vertical bar double right turnstile (⊫)
  ["\u22ac", "+"], // does not prove (⊬)
  ["\u22ad", "+"], // not true (⊭)
  ["\u22ae", "+"], // does not force (⊮)
  ["\u22af", "+"], // negated double vertical bar double right turnstile (⊯)
  ["\u22b0", "<"], // precedes under relation (⊰)
  ["\u22b1", ">"], // succeeds under relation (⊱)
  ["\u22b2", "<"], // normal subgroup of (⊲)
  ["\u22b3", ">"], // contains as normal subgroup (⊳)
  ["\u22b4", "<"], // normal subgroup of or equal to (⊴)
  ["\u22b5", ">"], // contains as normal subgroup or equal to (⊵)
  ["\u22b6", "-"], // original of (⊶)
  ["\u22b7", "-"], // image of (⊷)
  ["\u22b8", "-"], // multimap (⊸)
  ["\u22b9", "+"], // hermitian conjugate matrix (⊹)
  ["\u22ba", "T"], // intercalate (⊺)
  ["\u22bb", "v"], // xor (⊻)
  ["\u22bc", "^"], // nand (⊼)
  ["\u22bd", "v"], // nor (⊽)
  ["\u22be", "<"], // right angle with arc (⊾)
  ["\u22bf", "/"], // right triangle (⊿)
  ["\u22c0", "^"], // n-ary logical and (⋀)
  ["\u22c1", "v"], // n-ary logical or (⋁)
  ["\u22c2", "^"], // n-ary intersection (⋂)
  ["\u22c3", "v"], // n-ary union (⋃)
  ["\u22c4", "*"], // diamond operator (⋄)
  ["\u22c6", "*"], // star operator (⋆)
  ["\u22c7", "*"], // division times (⋇)
  ["\u22c8", "><"], // bowtie (⋈)
  ["\u22c9", "><"], // left normal factor semidirect product (⋉)
  ["\u22ca", "><"], // right normal factor semidirect product (⋊)
  ["\u22cb", ">"], // left semidirect product (⋋)
  ["\u22cc", "<"], // right semidirect product (⋌)
  ["\u22cd", "~="], // reversed tilde equals (⋍)
  ["\u22ce", "v"], // curly logical or (⋎)
  ["\u22cf", "^"], // curly logical and (⋏)
  ["\u22d0", "<"], // double subset (⋐)
  ["\u22d1", ">"], // double superset (⋑)
  ["\u22d2", "^"], // double intersection (⋒)
  ["\u22d3", "v"], // double union (⋓)
  ["\u22d4", "+"], // pitchfork (⋔)
  ["\u22d5", "#"], // equal and parallel to (⋕)
  ["\u22d6", "<"], // less-than with dot (⋖)
  ["\u22d7", ">"], // greater-than with dot (⋗)
  ["\u22d8", "<<<"], // very much less-than (⋘)
  ["\u22d9", ">>>"], // very much greater-than (⋙)
  ["\u22da", "="], // less-than equal to or greater-than (⋚)
  ["\u22db", "="], // greater-than equal to or less-than (⋛)
  ["\u22dc", "=<"], // equal to or less-than (⋜)
  ["\u22dd", "=>"], // equal to or greater-than (⋝)
  ["\u22de", "<"], // equal to or precedes (⋞)
  ["\u22df", ">"], // equal to or succeeds (⋟)
  ["\u22e0", "<"], // does not precede or equal (⋠)
  ["\u22e1", ">"], // does not succeed or equal (⋡)
  ["\u22e2", "["], // not square image of or equal to (⋢)
  ["\u22e3", "]"], // not square original of or equal to (⋣)
  ["\u22e4", "["], // square image of or not equal to (⋤)
  ["\u22e5", "]"], // square original of or not equal to (⋥)
  ["\u22e6", "<"], // less-than but not equivalent to (⋦)
  ["\u22e7", ">"], // greater-than but not equivalent to (⋧)
  ["\u22e8", "<"], // precedes but not equivalent to (⋨)
  ["\u22e9", ">"], // succeeds but not equivalent to (⋩)
  ["\u22ea", "<"], // not normal subgroup of (⋪)
  ["\u22eb", ">"], // does not contain as normal subgroup (⋫)
  ["\u22ec", "<"], // not normal subgroup of or equal to (⋬)
  ["\u22ed", ">"], // does not contain as normal subgroup or equal (⋭)
  ["\u22ee", "|"], // vertical ellipsis (⋮)
  ["\u22f0", "/"], // up right diagonal ellipsis (⋰)
  ["\u22f1", "\\"], // down right diagonal ellipsis (⋱)
  ["\u22f2", "+"], // element of with long horizontal stroke (⋲)
  ["\u22f3", "+"], // element of with vertical bar at end of horizontal stroke (⋳)
  ["\u22f4", "+"], // small element of with vertical bar at end of horizontal stroke (⋴)
  ["\u22f5", "+"], // element of with dot above (⋵)
  ["\u22f6", "+"], // element of with overbar (⋶)
  ["\u22f7", "+"], // small element of with overbar (⋷)
  ["\u22f8", "+"], // element of with underbar (⋸)
  ["\u22f9", "+"], // element of with two horizontal strokes (⋹)
  ["\u22fa", "+"], // contains with long horizontal stroke (⋺)
  ["\u22fb", "+"], // contains with vertical bar at end of horizontal stroke (⋻)
  ["\u22fc", "+"], // small contains with vertical bar at end of horizontal stroke (⋼)
  ["\u22fd", "+"], // contains with overbar (⋽)
  ["\u22fe", "+"], // small contains with overbar (⋾)
  ["\u22ff", "E"], // z notation bag membership (⋿)
];

export const EMOJIS: Array<[string, string]> = [
  // Checkmarks / cross marks
  ["\u2713", "v"], // check mark ([x])
  // The two unfilled members of the ballot-box family. The checked member ☑
  // mapped only to a :shortcode: label and is dropped; ☐ ☒ take the AnyAscii
  // single-char forms.
  ["\u2610", "#"], // ballot box ([ ])
  ["\u2612", "x"], // ballot box with x ([x])
  ["\u2717", "x"], // ballot x ([!])
  ["\u2718", "x"], // heavy ballot x ([!])
  // Info / ideas
  ["\u2139", "i"], // information source ([i])
  // Stars / rating
  ["\u2605", "*"], // black star ([*])
  ["\u2606", "*"], // white star ([*])
  // AnyAscii wholesale — Dingbats, Miscellaneous Symbols, Miscellaneous
  // Symbols and Pictographs, Miscellaneous Technical, Transport and Map. The
  // ">= 2 entries per block" rule is enforced by scripts/vendor-anyascii.py.
  ["\u2300", "0"], // diameter sign (⌀)
  ["\u2301", "~"], // electric arrow (⌁)
  ["\u2302", "^"], // house (⌂)
  ["\u2303", "^"], // up arrowhead (⌃)
  ["\u2304", "v"], // down arrowhead (⌄)
  ["\u2305", "^"], // projective (⌅)
  ["\u2306", "^"], // perspective (⌆)
  ["\u2307", "~"], // wavy line (⌇)
  ["\u2308", "["], // left ceiling (⌈)
  ["\u2309", "]"], // right ceiling (⌉)
  ["\u230a", "["], // left floor (⌊)
  ["\u230b", "]"], // right floor (⌋)
  ["\u230c", "+"], // bottom right crop (⌌)
  ["\u230d", "+"], // bottom left crop (⌍)
  ["\u230e", "+"], // top right crop (⌎)
  ["\u230f", "+"], // top left crop (⌏)
  ["\u2310", "-"], // reversed not sign (⌐)
  ["\u2311", "*"], // square lozenge (⌑)
  ["\u2312", "*"], // arc (⌒)
  ["\u2313", "*"], // segment (⌓)
  ["\u2314", "*"], // sector (⌔)
  ["\u2315", "*"], // telephone recorder (⌕)
  ["\u2316", "+"], // position indicator (⌖)
  ["\u2317", "#"], // viewdata square (⌗)
  ["\u2318", "#"], // place of interest sign (⌘)
  ["\u2319", "-"], // turned not sign (⌙)
  ["\u231c", "+"], // top left corner (⌜)
  ["\u231d", "+"], // top right corner (⌝)
  ["\u231e", "+"], // bottom left corner (⌞)
  ["\u231f", "+"], // bottom right corner (⌟)
  ["\u2320", "("], // top half integral (⌠)
  ["\u2321", ")"], // bottom half integral (⌡)
  ["\u2322", "("], // frown (⌢)
  ["\u2323", ")"], // smile (⌣)
  ["\u2324", "^"], // up arrowhead between two horizontal bars (⌤)
  ["\u2325", "*"], // option key (⌥)
  ["\u2326", ">"], // erase to the right (⌦)
  ["\u2327", "x"], // x in a rectangle box (⌧)
  ["\u2329", "<"], // left-pointing angle bracket (〈)
  ["\u232a", ">"], // right-pointing angle bracket (〉)
  ["\u232b", "<"], // erase to the left (⌫)
  ["\u232c", "#"], // benzene ring (⌬)
  ["\u232d", "*"], // cylindricity (⌭)
  ["\u232e", "*"], // all around-profile (⌮)
  ["\u232f", "*"], // symmetry (⌯)
  ["\u2330", "*"], // total runout (⌰)
  ["\u2331", "*"], // dimension origin (⌱)
  ["\u2332", "*"], // conical taper (⌲)
  ["\u2333", "*"], // slope (⌳)
  ["\u2334", "*"], // counterbore (⌴)
  ["\u2335", "*"], // countersink (⌵)
  ["\u2336", "I"], // apl functional symbol i-beam (⌶)
  ["\u2337", "#"], // apl functional symbol squish quad (⌷)
  ["\u2338", "="], // apl functional symbol quad equal (⌸)
  ["\u2339", ":"], // apl functional symbol quad divide (⌹)
  ["\u233a", "*"], // apl functional symbol quad diamond (⌺)
  ["\u233b", "*"], // apl functional symbol quad jot (⌻)
  ["\u233c", "*"], // apl functional symbol quad circle (⌼)
  ["\u233d", "*"], // apl functional symbol circle stile (⌽)
  ["\u233e", "*"], // apl functional symbol circle jot (⌾)
  ["\u233f", "/"], // apl functional symbol slash bar (⌿)
  ["\u2340", "\\"], // apl functional symbol backslash bar (⍀)
  ["\u2341", "/"], // apl functional symbol quad slash (⍁)
  ["\u2342", "\\"], // apl functional symbol quad backslash (⍂)
  ["\u2343", "<"], // apl functional symbol quad less-than (⍃)
  ["\u2344", ">"], // apl functional symbol quad greater-than (⍄)
  ["\u2345", "<"], // apl functional symbol leftwards vane (⍅)
  ["\u2346", ">"], // apl functional symbol rightwards vane (⍆)
  ["\u2347", "<"], // apl functional symbol quad leftwards arrow (⍇)
  ["\u2348", ">"], // apl functional symbol quad rightwards arrow (⍈)
  ["\u2349", "0"], // apl functional symbol circle backslash (⍉)
  ["\u234a", "*"], // apl functional symbol down tack underbar (⍊)
  ["\u234b", "*"], // apl functional symbol delta stile (⍋)
  ["\u234c", "v"], // apl functional symbol quad down caret (⍌)
  ["\u234d", "*"], // apl functional symbol quad delta (⍍)
  ["\u234e", "*"], // apl functional symbol down tack jot (⍎)
  ["\u234f", "^"], // apl functional symbol upwards vane (⍏)
  ["\u2350", "^"], // apl functional symbol quad upwards arrow (⍐)
  ["\u2351", "*"], // apl functional symbol up tack overbar (⍑)
  ["\u2352", "*"], // apl functional symbol del stile (⍒)
  ["\u2353", "^"], // apl functional symbol quad up caret (⍓)
  ["\u2354", "*"], // apl functional symbol quad del (⍔)
  ["\u2355", "*"], // apl functional symbol up tack jot (⍕)
  ["\u2356", "v"], // apl functional symbol downwards vane (⍖)
  ["\u2357", "v"], // apl functional symbol quad downwards arrow (⍗)
  ["\u2358", "'"], // apl functional symbol quote underbar (⍘)
  ["\u2359", "*"], // apl functional symbol delta underbar (⍙)
  ["\u235a", "*"], // apl functional symbol diamond underbar (⍚)
  ["\u235b", "*"], // apl functional symbol jot underbar (⍛)
  ["\u235c", "*"], // apl functional symbol circle underbar (⍜)
  ["\u235d", "*"], // apl functional symbol up shoe jot (⍝)
  ["\u235e", "'"], // apl functional symbol quote quad (⍞)
  ["\u235f", "*"], // apl functional symbol circle star (⍟)
  ["\u2360", ":"], // apl functional symbol quad colon (⍠)
  ["\u2361", "*"], // apl functional symbol up tack diaeresis (⍡)
  ["\u2362", "*"], // apl functional symbol del diaeresis (⍢)
  ["\u2363", "*"], // apl functional symbol star diaeresis (⍣)
  ["\u2364", "*"], // apl functional symbol jot diaeresis (⍤)
  ["\u2365", "*"], // apl functional symbol circle diaeresis (⍥)
  ["\u2366", "*"], // apl functional symbol down shoe stile (⍦)
  ["\u2367", "*"], // apl functional symbol left shoe stile (⍧)
  ["\u2368", "~"], // apl functional symbol tilde diaeresis (⍨)
  ["\u2369", ">"], // apl functional symbol greater-than diaeresis (⍩)
  ["\u236a", ","], // apl functional symbol comma bar (⍪)
  ["\u236b", "*"], // apl functional symbol del tilde (⍫)
  ["\u236c", "0"], // apl functional symbol zilde (⍬)
  ["\u236d", "|"], // apl functional symbol stile tilde (⍭)
  ["\u236e", ";"], // apl functional symbol semicolon underbar (⍮)
  ["\u236f", "="], // apl functional symbol quad not equal (⍯)
  ["\u2370", "?"], // apl functional symbol quad question (⍰)
  ["\u2371", "v"], // apl functional symbol down caret tilde (⍱)
  ["\u2372", "^"], // apl functional symbol up caret tilde (⍲)
  ["\u2373", "i"], // apl functional symbol iota (⍳)
  ["\u2374", "r"], // apl functional symbol rho (⍴)
  ["\u2375", "o"], // apl functional symbol omega (⍵)
  ["\u2376", "a"], // apl functional symbol alpha underbar (⍶)
  ["\u2377", "e"], // apl functional symbol epsilon underbar (⍷)
  ["\u2378", "i"], // apl functional symbol iota underbar (⍸)
  ["\u2379", "o"], // apl functional symbol omega underbar (⍹)
  ["\u237a", "a"], // apl functional symbol alpha (⍺)
  ["\u237b", "NAK"], // not check mark (⍻)
  ["\u237c", "+"], // right angle with downwards zigzag arrow (⍼)
  ["\u237d", "*"], // shouldered open box (⍽)
  ["\u237e", "*"], // bell symbol (⍾)
  ["\u237f", "|"], // vertical line with middle dot (⍿)
  ["\u2380", "*"], // insertion symbol (⎀)
  ["\u2381", "*"], // continuous underline symbol (⎁)
  ["\u2382", "*"], // discontinuous underline symbol (⎂)
  ["\u2383", "*"], // emphasis symbol (⎃)
  ["\u2384", "*"], // composition symbol (⎄)
  ["\u2385", "*"], // white square with centre vertical line (⎅)
  ["\u2386", "*"], // enter symbol (⎆)
  ["\u2387", "*"], // alternative key symbol (⎇)
  ["\u2388", "*"], // helm symbol (⎈)
  ["\u2389", "*"], // circled horizontal bar with notch (⎉)
  ["\u238a", "*"], // circled triangle down (⎊)
  ["\u238b", "*"], // broken circle with northwest arrow (⎋)
  ["\u238c", "*"], // undo symbol (⎌)
  ["\u238d", "*"], // monostable symbol (⎍)
  ["\u238e", "*"], // hysteresis symbol (⎎)
  ["\u238f", "*"], // open-circuit-output h-type symbol (⎏)
  ["\u2390", "*"], // open-circuit-output l-type symbol (⎐)
  ["\u2391", "*"], // passive-pull-down-output symbol (⎑)
  ["\u2392", "*"], // passive-pull-up-output symbol (⎒)
  ["\u2393", "*"], // direct current symbol form two (⎓)
  ["\u2394", "*"], // software-function symbol (⎔)
  ["\u2395", "#"], // apl functional symbol quad (⎕)
  ["\u2396", "."], // decimal separator key symbol (⎖)
  ["\u2397", "<"], // previous page (⎗)
  ["\u2398", ">"], // next page (⎘)
  ["\u2399", "#"], // print screen symbol (⎙)
  ["\u239a", "#"], // clear screen symbol (⎚)
  ["\u239b", "("], // left parenthesis upper hook (⎛)
  ["\u239c", "("], // left parenthesis extension (⎜)
  ["\u239d", "("], // left parenthesis lower hook (⎝)
  ["\u239e", ")"], // right parenthesis upper hook (⎞)
  ["\u239f", ")"], // right parenthesis extension (⎟)
  ["\u23a0", ")"], // right parenthesis lower hook (⎠)
  ["\u23a1", "["], // left square bracket upper corner (⎡)
  ["\u23a2", "["], // left square bracket extension (⎢)
  ["\u23a3", "["], // left square bracket lower corner (⎣)
  ["\u23a4", "]"], // right square bracket upper corner (⎤)
  ["\u23a5", "]"], // right square bracket extension (⎥)
  ["\u23a6", "]"], // right square bracket lower corner (⎦)
  ["\u23a7", "{"], // left curly bracket upper hook (⎧)
  ["\u23a8", "{"], // left curly bracket middle piece (⎨)
  ["\u23a9", "{"], // left curly bracket lower hook (⎩)
  ["\u23aa", "|"], // curly bracket extension (⎪)
  ["\u23ab", "}"], // right curly bracket upper hook (⎫)
  ["\u23ac", "}"], // right curly bracket middle piece (⎬)
  ["\u23ad", "}"], // right curly bracket lower hook (⎭)
  ["\u23ae", "|"], // integral extension (⎮)
  ["\u23af", "-"], // horizontal line extension (⎯)
  ["\u23b0", "{"], // upper left or lower right curly bracket section (⎰)
  ["\u23b1", "{"], // upper right or lower left curly bracket section (⎱)
  ["\u23b2", "S"], // summation top (⎲)
  ["\u23b3", "S"], // summation bottom (⎳)
  ["\u23b4", "["], // top square bracket (⎴)
  ["\u23b5", "]"], // bottom square bracket (⎵)
  ["\u23b6", "]["], // bottom square bracket over top square bracket (⎶)
  ["\u23b7", "/"], // radical symbol bottom (⎷)
  ["\u23b8", "|"], // left vertical box line (⎸)
  ["\u23b9", "|"], // right vertical box line (⎹)
  ["\u23ba", "-"], // horizontal scan line-1 (⎺)
  ["\u23bb", "-"], // horizontal scan line-3 (⎻)
  ["\u23bc", "-"], // horizontal scan line-7 (⎼)
  ["\u23bd", "-"], // horizontal scan line-9 (⎽)
  ["\u23be", "+"], // dentistry symbol light vertical and top right (⎾)
  ["\u23bf", "+"], // dentistry symbol light vertical and bottom right (⎿)
  ["\u23c0", "+"], // dentistry symbol light vertical with circle (⏀)
  ["\u23c1", "+"], // dentistry symbol light down and horizontal with circle (⏁)
  ["\u23c2", "+"], // dentistry symbol light up and horizontal with circle (⏂)
  ["\u23c3", "+"], // dentistry symbol light vertical with triangle (⏃)
  ["\u23c4", "+"], // dentistry symbol light down and horizontal with triangle (⏄)
  ["\u23c5", "+"], // dentistry symbol light up and horizontal with triangle (⏅)
  ["\u23c6", "+"], // dentistry symbol light vertical and wave (⏆)
  ["\u23c7", "+"], // dentistry symbol light down and horizontal with wave (⏇)
  ["\u23c8", "+"], // dentistry symbol light up and horizontal with wave (⏈)
  ["\u23c9", "+"], // dentistry symbol light down and horizontal (⏉)
  ["\u23ca", "+"], // dentistry symbol light up and horizontal (⏊)
  ["\u23cb", "+"], // dentistry symbol light vertical and top left (⏋)
  ["\u23cc", "+"], // dentistry symbol light vertical and bottom left (⏌)
  ["\u23cd", "'"], // square foot (⏍)
  ["\u23ce", "<"], // return symbol (⏎)
  ["\u23d0", "|"], // vertical line extension (⏐)
  ["\u23d1", "-"], // metrical breve (⏑)
  ["\u23d2", "-"], // metrical long over short (⏒)
  ["\u23d3", "-"], // metrical short over long (⏓)
  ["\u23d4", "-"], // metrical long over two shorts (⏔)
  ["\u23d5", "-"], // metrical two shorts over long (⏕)
  ["\u23d6", "-"], // metrical two shorts joined (⏖)
  ["\u23d7", "3"], // metrical triseme (⏗)
  ["\u23d8", "4"], // metrical tetraseme (⏘)
  ["\u23d9", "5"], // metrical pentaseme (⏙)
  ["\u23da", "+"], // earth ground (⏚)
  ["\u23db", "-"], // fuse (⏛)
  ["\u23dc", "("], // top parenthesis (⏜)
  ["\u23dd", ")"], // bottom parenthesis (⏝)
  ["\u23de", "{"], // top curly bracket (⏞)
  ["\u23df", "}"], // bottom curly bracket (⏟)
  ["\u23e0", "["], // top tortoise shell bracket (⏠)
  ["\u23e1", "]"], // bottom tortoise shell bracket (⏡)
  ["\u23e2", "#"], // white trapezium (⏢)
  ["\u23e3", "#"], // benzene ring with circle (⏣)
  ["\u23e4", "-"], // straightness (⏤)
  ["\u23e5", "#"], // flatness (⏥)
  ["\u23e6", "*"], // ac current (⏦)
  ["\u23e7", "*"], // electrical intersection (⏧)
  ["\u23e8", "E"], // decimal exponent symbol (⏨)
  ["\u23f4", "<"], // black medium left-pointing triangle (⏴)
  ["\u23f5", ">"], // black medium right-pointing triangle (⏵)
  ["\u23f6", "^"], // black medium up-pointing triangle (⏶)
  ["\u23f7", "v"], // black medium down-pointing triangle (⏷)
  ["\u23fb", "*"], // power symbol (⏻)
  ["\u23fc", "*"], // power on-off symbol (⏼)
  ["\u23fd", "*"], // power on symbol (⏽)
  ["\u23fe", "*"], // power sleep symbol (⏾)
  ["\u23ff", "<"], // observer eye symbol (⏿)
  ["\u2607", "*"], // lightning (☇)
  ["\u2608", "*"], // thunderstorm (☈)
  ["\u2609", "*"], // sun (☉)
  ["\u260a", "*"], // ascending node (☊)
  ["\u260b", "*"], // descending node (☋)
  ["\u260c", "0"], // conjunction (☌)
  ["\u260d", "180"], // opposition (☍)
  ["\u260f", "@"], // white telephone (☏)
  ["\u2613", "X"], // saltire (☓)
  ["\u2616", "W"], // white shogi piece (☖)
  ["\u2617", "B"], // black shogi piece (☗)
  ["\u2619", "*"], // reversed rotated floral heart bullet (☙)
  ["\u261a", "<"], // black left pointing index (☚)
  ["\u261b", ">"], // black right pointing index (☛)
  ["\u261c", "<"], // white left pointing index (☜)
  ["\u261e", ">"], // white right pointing index (☞)
  ["\u261f", "v"], // white down pointing index (☟)
  ["\u2621", "Z"], // caution sign (☡)
  ["\u2624", "+"], // caduceus (☤)
  ["\u2625", "+"], // ankh (☥)
  ["\u2627", "ChR."], // chi rho (☧)
  ["\u2628", "+"], // cross of lorraine (☨)
  ["\u2629", "+"], // cross of jerusalem (☩)
  ["\u262b", "*"], // farsi symbol (☫)
  ["\u262c", "*"], // adi shakti (☬)
  ["\u262d", "*"], // hammer and sickle (☭)
  ["\u2630", "Qian"], // trigram for heaven (☰)
  ["\u2631", "Dui"], // trigram for lake (☱)
  ["\u2632", "Li"], // trigram for fire (☲)
  ["\u2633", "Zhen"], // trigram for thunder (☳)
  ["\u2634", "Xun"], // trigram for wind (☴)
  ["\u2635", "Kan"], // trigram for water (☵)
  ["\u2636", "Gen"], // trigram for mountain (☶)
  ["\u2637", "Kun"], // trigram for earth (☷)
  ["\u263b", ":)"], // black smiling face (☻)
  ["\u263c", "*"], // white sun with rays (☼)
  ["\u263d", ")"], // first quarter moon (☽)
  ["\u263e", "("], // last quarter moon (☾)
  ["\u263f", "Mercury"], // mercury (☿)
  ["\u2641", "Earth"], // earth (♁)
  ["\u2643", "Jupiter"], // jupiter (♃)
  ["\u2644", "Saturn"], // saturn (♄)
  ["\u2645", "Uranus"], // uranus (♅)
  ["\u2646", "Neptune"], // neptune (♆)
  ["\u2647", "Pluto"], // pluto (♇)
  ["\u2654", "K"], // white chess king (♔)
  ["\u2655", "Q"], // white chess queen (♕)
  ["\u2656", "R"], // white chess rook (♖)
  ["\u2657", "B"], // white chess bishop (♗)
  ["\u2658", "N"], // white chess knight (♘)
  ["\u2659", "P"], // white chess pawn (♙)
  ["\u265a", "k"], // black chess king (♚)
  ["\u265b", "q"], // black chess queen (♛)
  ["\u265c", "r"], // black chess rook (♜)
  ["\u265d", "b"], // black chess bishop (♝)
  ["\u265e", "n"], // black chess knight (♞)
  ["\u2661", "H"], // white heart suit (♡)
  ["\u2662", "D"], // white diamond suit (♢)
  ["\u2664", "S"], // white spade suit (♤)
  ["\u2667", "C"], // white club suit (♧)
  ["\u2669", "#"], // quarter note (♩)
  ["\u266a", "#"], // eighth note (♪)
  ["\u266b", "#"], // beamed eighth notes (♫)
  ["\u266c", "#"], // beamed sixteenth notes (♬)
  ["\u266d", "b"], // music flat sign (♭)
  ["\u266e", "#"], // music natural sign (♮)
  ["\u266f", "#"], // music sharp sign (♯)
  ["\u2670", "+"], // west syriac cross (♰)
  ["\u2671", "+"], // east syriac cross (♱)
  ["\u2672", "*"], // universal recycling symbol (♲)
  ["\u2673", "1"], // recycling symbol for type-1 plastics (♳)
  ["\u2674", "2"], // recycling symbol for type-2 plastics (♴)
  ["\u2675", "3"], // recycling symbol for type-3 plastics (♵)
  ["\u2676", "4"], // recycling symbol for type-4 plastics (♶)
  ["\u2677", "5"], // recycling symbol for type-5 plastics (♷)
  ["\u2678", "6"], // recycling symbol for type-6 plastics (♸)
  ["\u2679", "7"], // recycling symbol for type-7 plastics (♹)
  ["\u267a", "*"], // recycling symbol for generic materials (♺)
  ["\u267c", "*"], // recycled paper symbol (♼)
  ["\u267d", "*"], // partially-recycled paper symbol (♽)
  ["\u2680", "1"], // die face-1 (⚀)
  ["\u2681", "2"], // die face-2 (⚁)
  ["\u2682", "3"], // die face-3 (⚂)
  ["\u2683", "4"], // die face-4 (⚃)
  ["\u2684", "5"], // die face-5 (⚄)
  ["\u2685", "6"], // die face-6 (⚅)
  ["\u2686", "*"], // white circle with dot right (⚆)
  ["\u2687", "*"], // white circle with two dots (⚇)
  ["\u2688", "*"], // black circle with white dot right (⚈)
  ["\u2689", "*"], // black circle with two white dots (⚉)
  ["\u268a", "YangYao"], // monogram for yang (⚊)
  ["\u268b", "YinYao"], // monogram for yin (⚋)
  ["\u268c", "TaiYang"], // digram for greater yang (⚌)
  ["\u268d", "ShaoYin"], // digram for lesser yin (⚍)
  ["\u268e", "ShaoYang"], // digram for lesser yang (⚎)
  ["\u268f", "TaiYin"], // digram for greater yin (⚏)
  ["\u2690", "*"], // white flag (⚐)
  ["\u2691", "*"], // black flag (⚑)
  ["\u2698", "*"], // flower (⚘)
  ["\u269a", "*"], // staff of hermes (⚚)
  ["\u269d", "*"], // outlined white star (⚝)
  ["\u269e", ">"], // three lines converging right (⚞)
  ["\u269f", "<"], // three lines converging left (⚟)
  ["\u26a2", "*"], // doubled female sign (⚢)
  ["\u26a3", "*"], // doubled male sign (⚣)
  ["\u26a4", "*"], // interlocked female and male sign (⚤)
  ["\u26a5", "*"], // male and female sign (⚥)
  ["\u26a6", "*"], // male with stroke sign (⚦)
  ["\u26a8", "*"], // vertical male with stroke sign (⚨)
  ["\u26a9", "*"], // horizontal male with stroke sign (⚩)
  ["\u26ac", "*"], // medium small white circle (⚬)
  ["\u26ad", "*"], // marriage symbol (⚭)
  ["\u26ae", "*"], // divorce symbol (⚮)
  ["\u26af", "*"], // unmarried partnership symbol (⚯)
  ["\u26b2", "*"], // neuter (⚲)
  ["\u26b3", "*"], // ceres (⚳)
  ["\u26b4", "*"], // pallas (⚴)
  ["\u26b5", "*"], // juno (⚵)
  ["\u26b6", "*"], // vesta (⚶)
  ["\u26b7", "*"], // chiron (⚷)
  ["\u26b8", "*"], // black moon lilith (⚸)
  ["\u26b9", "*"], // sextile (⚹)
  ["\u26ba", "30"], // semisextile (⚺)
  ["\u26bb", "150"], // quincunx (⚻)
  ["\u26bc", "135"], // sesquiquadrate (⚼)
  ["\u26bf", "*"], // squared key (⚿)
  ["\u26c0", "M"], // white draughts man (⛀)
  ["\u26c1", "K"], // white draughts king (⛁)
  ["\u26c2", "m"], // black draughts man (⛂)
  ["\u26c3", "k"], // black draughts king (⛃)
  ["\u26c6", "*"], // rain (⛆)
  ["\u26c7", "*"], // black snowman (⛇)
  ["\u26c9", "w"], // turned white shogi piece (⛉)
  ["\u26ca", "b"], // turned black shogi piece (⛊)
  ["\u26cb", "#"], // white diamond in square (⛋)
  ["\u26cc", "X"], // crossing lanes (⛌)
  ["\u26cd", "*"], // disabled car (⛍)
  ["\u26d0", "*"], // car sliding (⛐)
  ["\u26d2", "*"], // circled crossing lanes (⛒)
  ["\u26d5", "*"], // alternate one-way left way traffic (⛕)
  ["\u26d6", "*"], // black two-way left way traffic (⛖)
  ["\u26d7", "*"], // white two-way left way traffic (⛗)
  ["\u26d8", "*"], // black left lane merge (⛘)
  ["\u26d9", "*"], // white left lane merge (⛙)
  ["\u26da", "*"], // drive slow sign (⛚)
  ["\u26db", "v"], // heavy white down-pointing triangle (⛛)
  ["\u26dc", "*"], // left closed entry (⛜)
  ["\u26dd", "X"], // squared saltire (⛝)
  ["\u26de", "\\"], // falling diagonal in white circle in black square (⛞)
  ["\u26df", "*"], // black truck (⛟)
  ["\u26e0", "*"], // restricted left entry-1 (⛠)
  ["\u26e1", "*"], // restricted left entry-2 (⛡)
  ["\u26e2", "Uranus"], // astronomical symbol for uranus (⛢)
  ["\u26e3", "*"], // heavy circle with stroke and two dots above (⛣)
  ["\u26e4", "*"], // pentagram (⛤)
  ["\u26e5", "*"], // right-handed interlaced pentagram (⛥)
  ["\u26e6", "*"], // left-handed interlaced pentagram (⛦)
  ["\u26e7", "*"], // inverted pentagram (⛧)
  ["\u26e8", "+"], // black cross on shield (⛨)
  ["\u26eb", "*"], // castle (⛫)
  ["\u26ec", "*"], // historic site (⛬)
  ["\u26ed", "*"], // gear without hub (⛭)
  ["\u26ee", "*"], // gear with handles (⛮)
  ["\u26ef", "*"], // map symbol for lighthouse (⛯)
  ["\u26f6", "#"], // square four corners (⛶)
  ["\u26fb", "*"], // japanese bank symbol (⛻)
  ["\u26fc", "*"], // headstone graveyard symbol (⛼)
  ["\u26fe", "*"], // cup on black square (⛾)
  ["\u26ff", "*"], // white flag with horizontal middle black stripe (⛿)
  ["\u2700", "<"], // black safety scissors (✀)
  ["\u2701", "<"], // upper blade scissors (✁)
  ["\u2703", "<"], // lower blade scissors (✃)
  ["\u2704", "<"], // white scissors (✄)
  ["\u2706", "@"], // telephone location sign (✆)
  ["\u2707", "@"], // tape drive (✇)
  ["\u270e", "\\"], // lower right pencil (✎)
  ["\u2710", "/"], // upper right pencil (✐)
  ["\u2711", ">"], // white nib (✑)
  ["\u2715", "X"], // multiplication x (✕)
  ["\u2719", "+"], // outlined greek cross (✙)
  ["\u271a", "+"], // heavy greek cross (✚)
  ["\u271b", "+"], // open centre cross (✛)
  ["\u271c", "+"], // heavy open centre cross (✜)
  ["\u271e", "+"], // shadowed white latin cross (✞)
  ["\u271f", "+"], // outlined latin cross (✟)
  ["\u2720", "+"], // maltese cross (✠)
  ["\u2722", "*"], // four teardrop-spoked asterisk (✢)
  ["\u2723", "*"], // four balloon-spoked asterisk (✣)
  ["\u2724", "*"], // heavy four balloon-spoked asterisk (✤)
  ["\u2725", "*"], // four club-spoked asterisk (✥)
  ["\u2726", "*"], // black four pointed star (✦)
  ["\u2727", "*"], // white four pointed star (✧)
  ["\u2729", "*"], // stress outlined white star (✩)
  ["\u272a", "*"], // circled white star (✪)
  ["\u272b", "*"], // open centre black star (✫)
  ["\u272c", "*"], // black centre white star (✬)
  ["\u272d", "*"], // outlined black star (✭)
  ["\u272e", "*"], // heavy outlined black star (✮)
  ["\u272f", "*"], // pinwheel star (✯)
  ["\u2730", "*"], // shadowed white star (✰)
  ["\u2731", "*"], // heavy asterisk (✱)
  ["\u2732", "*"], // open centre asterisk (✲)
  ["\u2735", "*"], // eight pointed pinwheel star (✵)
  ["\u2736", "*"], // six pointed black star (✶)
  ["\u2737", "*"], // eight pointed rectilinear black star (✷)
  ["\u2738", "*"], // heavy eight pointed rectilinear black star (✸)
  ["\u2739", "*"], // twelve pointed black star (✹)
  ["\u273a", "*"], // sixteen pointed asterisk (✺)
  ["\u273b", "*"], // teardrop-spoked asterisk (✻)
  ["\u273c", "*"], // open centre teardrop-spoked asterisk (✼)
  ["\u273d", "*"], // heavy teardrop-spoked asterisk (✽)
  ["\u273e", "*"], // six petalled black and white florette (✾)
  ["\u273f", "*"], // black florette (✿)
  ["\u2740", "*"], // white florette (❀)
  ["\u2741", "*"], // eight petalled outlined black florette (❁)
  ["\u2742", "*"], // circled open centre eight pointed star (❂)
  ["\u2743", "*"], // heavy teardrop-spoked pinwheel asterisk (❃)
  ["\u2745", "*"], // tight trifoliate snowflake (❅)
  ["\u2746", "*"], // heavy chevron snowflake (❆)
  ["\u2748", "*"], // heavy sparkle (❈)
  ["\u2749", "*"], // balloon-spoked asterisk (❉)
  ["\u274a", "*"], // eight teardrop-spoked propeller asterisk (❊)
  ["\u274b", "*"], // heavy eight teardrop-spoked propeller asterisk (❋)
  ["\u274d", "*"], // shadowed white circle (❍)
  ["\u274f", "#"], // lower right drop-shadowed white square (❏)
  ["\u2750", "#"], // upper right drop-shadowed white square (❐)
  ["\u2751", "#"], // lower right shadowed white square (❑)
  ["\u2752", "#"], // upper right shadowed white square (❒)
  ["\u2756", "*"], // black diamond minus white x (❖)
  ["\u2758", "|"], // light vertical bar (❘)
  ["\u2759", "|"], // medium vertical bar (❙)
  ["\u275a", "|"], // heavy vertical bar (❚)
  ["\u275b", "'"], // heavy single turned comma quotation mark ornament (❛)
  ["\u275c", "'"], // heavy single comma quotation mark ornament (❜)
  ["\u275d", '"'], // heavy double turned comma quotation mark ornament (❝)
  ["\u275e", '"'], // heavy double comma quotation mark ornament (❞)
  ["\u275f", "'"], // heavy low single comma quotation mark ornament (❟)
  ["\u2760", '"'], // heavy low double comma quotation mark ornament (❠)
  ["\u2761", "P"], // curved stem paragraph sign ornament (❡)
  ["\u2762", "!"], // heavy exclamation mark ornament (❢)
  ["\u2765", "*"], // rotated heavy black heart bullet (❥)
  ["\u2766", "*"], // floral heart (❦)
  ["\u2767", "*"], // rotated floral heart bullet (❧)
  ["\u2768", "("], // medium left parenthesis ornament (❨)
  ["\u2769", ")"], // medium right parenthesis ornament (❩)
  ["\u276a", "("], // medium flattened left parenthesis ornament (❪)
  ["\u276b", ")"], // medium flattened right parenthesis ornament (❫)
  ["\u276c", "<"], // medium left-pointing angle bracket ornament (❬)
  ["\u276d", ">"], // medium right-pointing angle bracket ornament (❭)
  ["\u276e", "<"], // heavy left-pointing angle quotation mark ornament (❮)
  ["\u276f", ">"], // heavy right-pointing angle quotation mark ornament (❯)
  ["\u2770", "<"], // heavy left-pointing angle bracket ornament (❰)
  ["\u2771", ">"], // heavy right-pointing angle bracket ornament (❱)
  ["\u2772", "("], // light left tortoise shell bracket ornament (❲)
  ["\u2773", ")"], // light right tortoise shell bracket ornament (❳)
  ["\u2774", "{"], // medium left curly bracket ornament (❴)
  ["\u2775", "}"], // medium right curly bracket ornament (❵)
  ["\u2776", "1"], // dingbat negative circled digit one (❶)
  ["\u2777", "2"], // dingbat negative circled digit two (❷)
  ["\u2778", "3"], // dingbat negative circled digit three (❸)
  ["\u2779", "4"], // dingbat negative circled digit four (❹)
  ["\u277a", "5"], // dingbat negative circled digit five (❺)
  ["\u277b", "6"], // dingbat negative circled digit six (❻)
  ["\u277c", "7"], // dingbat negative circled digit seven (❼)
  ["\u277d", "8"], // dingbat negative circled digit eight (❽)
  ["\u277e", "9"], // dingbat negative circled digit nine (❾)
  ["\u277f", "10"], // dingbat negative circled number ten (❿)
  ["\u2780", "1"], // dingbat circled sans-serif digit one (➀)
  ["\u2781", "2"], // dingbat circled sans-serif digit two (➁)
  ["\u2782", "3"], // dingbat circled sans-serif digit three (➂)
  ["\u2783", "4"], // dingbat circled sans-serif digit four (➃)
  ["\u2784", "5"], // dingbat circled sans-serif digit five (➄)
  ["\u2785", "6"], // dingbat circled sans-serif digit six (➅)
  ["\u2786", "7"], // dingbat circled sans-serif digit seven (➆)
  ["\u2787", "8"], // dingbat circled sans-serif digit eight (➇)
  ["\u2788", "9"], // dingbat circled sans-serif digit nine (➈)
  ["\u2789", "10"], // dingbat circled sans-serif number ten (➉)
  ["\u278a", "1"], // dingbat negative circled sans-serif digit one (➊)
  ["\u278b", "2"], // dingbat negative circled sans-serif digit two (➋)
  ["\u278c", "3"], // dingbat negative circled sans-serif digit three (➌)
  ["\u278d", "4"], // dingbat negative circled sans-serif digit four (➍)
  ["\u278e", "5"], // dingbat negative circled sans-serif digit five (➎)
  ["\u278f", "6"], // dingbat negative circled sans-serif digit six (➏)
  ["\u2790", "7"], // dingbat negative circled sans-serif digit seven (➐)
  ["\u2791", "8"], // dingbat negative circled sans-serif digit eight (➑)
  ["\u2792", "9"], // dingbat negative circled sans-serif digit nine (➒)
  ["\u2793", "10"], // dingbat negative circled sans-serif number ten (➓)
  ["\u2798", "\\"], // heavy south east arrow (➘)
  ["\u2799", ">"], // heavy rightwards arrow (➙)
  ["\u279a", "/"], // heavy north east arrow (➚)
  ["\u279b", ">"], // drafting point rightwards arrow (➛)
  ["\u279f", ">"], // dashed triangle-headed rightwards arrow (➟)
  ["\u27a2", ">"], // three-d top-lighted rightwards arrowhead (➢)
  ["\u27a3", ">"], // three-d bottom-lighted rightwards arrowhead (➣)
  ["\u27a5", ">"], // heavy black curved downwards and rightwards arrow (➥)
  ["\u27a6", ">"], // heavy black curved upwards and rightwards arrow (➦)
  ["\u27a7", ">"], // squat black rightwards arrow (➧)
  ["\u27a8", ">"], // heavy concave-pointed black rightwards arrow (➨)
  ["\u27a9", ">"], // right-shaded white rightwards arrow (➩)
  ["\u27aa", ">"], // left-shaded white rightwards arrow (➪)
  ["\u27ab", ">"], // back-tilted shadowed white rightwards arrow (➫)
  ["\u27ac", ">"], // front-tilted shadowed white rightwards arrow (➬)
  ["\u27ad", ">"], // heavy lower right-shadowed white rightwards arrow (➭)
  ["\u27ae", ">"], // heavy upper right-shadowed white rightwards arrow (➮)
  ["\u27af", ">"], // notched lower right-shadowed white rightwards arrow (➯)
  ["\u27b1", ">"], // notched upper right-shadowed white rightwards arrow (➱)
  ["\u27b2", ">"], // circled heavy white rightwards arrow (➲)
  ["\u27b3", ">"], // white-feathered rightwards arrow (➳)
  ["\u27b4", "\\"], // black-feathered south east arrow (➴)
  ["\u27b5", ">"], // black-feathered rightwards arrow (➵)
  ["\u27b6", "/"], // black-feathered north east arrow (➶)
  ["\u27b7", "\\"], // heavy black-feathered south east arrow (➷)
  ["\u27b8", ">"], // heavy black-feathered rightwards arrow (➸)
  ["\u27b9", "/"], // heavy black-feathered north east arrow (➹)
  ["\u27ba", ">"], // teardrop-barbed rightwards arrow (➺)
  ["\u27bb", ">"], // heavy teardrop-shanked rightwards arrow (➻)
  ["\u27bc", ">"], // wedge-tailed rightwards arrow (➼)
  ["\u27bd", ">"], // heavy wedge-tailed rightwards arrow (➽)
  ["\u27be", ">"], // open-outlined rightwards arrow (➾)
  ["\u{1F322}", "*"], // black droplet (🌢)
  ["\u{1F323}", "*"], // white sun (🌣)
  ["\u{1F394}", "*"], // heart with tip on the left (🎔)
  ["\u{1F395}", "*"], // bouquet of flowers (🎕)
  ["\u{1F398}", "*"], // musical keyboard with jacks (🎘)
  ["\u{1F39C}", "#"], // beamed ascending musical notes (🎜)
  ["\u{1F39D}", "#"], // beamed descending musical notes (🎝)
  ["\u{1F3F1}", "*"], // white pennant (🏱)
  ["\u{1F3F2}", "*"], // black pennant (🏲)
  ["\u{1F3F6}", "*"], // black rosette (🏶)
  ["\u{1F4FE}", "*"], // portable stereo (📾)
  ["\u{1F53E}", "*"], // lower right shadowed white circle (🔾)
  ["\u{1F53F}", "*"], // upper right shadowed white circle (🔿)
  ["\u{1F540}", "+"], // circled cross pommee (🕀)
  ["\u{1F541}", "+"], // cross pommee with half-circle below (🕁)
  ["\u{1F542}", "+"], // cross pommee (🕂)
  ["\u{1F543}", "*"], // notched left semicircle with three dots (🕃)
  ["\u{1F544}", "*"], // notched right semicircle with three dots (🕄)
  ["\u{1F545}", "M"], // symbol for marks chapter (🕅)
  ["\u{1F546}", "+"], // white latin cross (🕆)
  ["\u{1F547}", "+"], // heavy latin cross (🕇)
  ["\u{1F548}", "+"], // celtic cross (🕈)
  ["\u{1F54F}", "*"], // bowl of hygieia (🕏)
  ["\u{1F568}", "*"], // right speaker (🕨)
  ["\u{1F569}", "*"], // right speaker with one sound wave (🕩)
  ["\u{1F56A}", "*"], // right speaker with three sound waves (🕪)
  ["\u{1F56B}", "@"], // bullhorn (🕫)
  ["\u{1F56C}", "@"], // bullhorn with sound waves (🕬)
  ["\u{1F56D}", "*"], // ringing bell (🕭)
  ["\u{1F56E}", "*"], // book (🕮)
  ["\u{1F571}", "*"], // black skull and crossbones (🕱)
  ["\u{1F572}", "*"], // no piracy (🕲)
  ["\u{1F57B}", "@"], // left hand telephone receiver (🕻)
  ["\u{1F57C}", "@"], // telephone receiver with page (🕼)
  ["\u{1F57D}", "@"], // right hand telephone receiver (🕽)
  ["\u{1F57E}", "@"], // white touchtone telephone (🕾)
  ["\u{1F57F}", "@"], // black touchtone telephone (🕿)
  ["\u{1F580}", "@"], // telephone on top of modem (🖀)
  ["\u{1F581}", "@"], // clamshell mobile phone (🖁)
  ["\u{1F582}", "@"], // back of envelope (🖂)
  ["\u{1F583}", "@"], // stamped envelope (🖃)
  ["\u{1F584}", "@"], // envelope with lightning (🖄)
  ["\u{1F585}", "@"], // flying envelope (🖅)
  ["\u{1F586}", "@"], // pen over stamped envelope (🖆)
  ["\u{1F588}", "*"], // black pushpin (🖈)
  ["\u{1F589}", "*"], // lower left pencil (🖉)
  ["\u{1F58E}", "*"], // left writing hand (🖎)
  ["\u{1F58F}", "*"], // turned ok hand sign (🖏)
  ["\u{1F591}", "*"], // reversed raised hand with fingers splayed (🖑)
  ["\u{1F592}", "^"], // reversed thumbs up sign (🖒)
  ["\u{1F593}", "v"], // reversed thumbs down sign (🖓)
  ["\u{1F594}", "V"], // reversed victory hand (🖔)
  ["\u{1F597}", "v"], // white down pointing left hand index (🖗)
  ["\u{1F598}", "<"], // sideways white left pointing index (🖘)
  ["\u{1F599}", ">"], // sideways white right pointing index (🖙)
  ["\u{1F59A}", "<"], // sideways black left pointing index (🖚)
  ["\u{1F59B}", ">"], // sideways black right pointing index (🖛)
  ["\u{1F59C}", "<"], // black left pointing backhand index (🖜)
  ["\u{1F59D}", ">"], // black right pointing backhand index (🖝)
  ["\u{1F59E}", "^"], // sideways white up pointing index (🖞)
  ["\u{1F59F}", "v"], // sideways white down pointing index (🖟)
  ["\u{1F5A0}", "^"], // sideways black up pointing index (🖠)
  ["\u{1F5A1}", "v"], // sideways black down pointing index (🖡)
  ["\u{1F5A2}", "^"], // black up pointing backhand index (🖢)
  ["\u{1F5A3}", "v"], // black down pointing backhand index (🖣)
  ["\u{1F5A6}", "*"], // keyboard and mouse (🖦)
  ["\u{1F5A7}", "*"], // three networked computers (🖧)
  ["\u{1F5A9}", "*"], // pocket calculator (🖩)
  ["\u{1F5AA}", "*"], // black hard shell floppy disk (🖪)
  ["\u{1F5AB}", "*"], // white hard shell floppy disk (🖫)
  ["\u{1F5AC}", "*"], // soft shell floppy disk (🖬)
  ["\u{1F5AD}", "*"], // tape cartridge (🖭)
  ["\u{1F5AE}", "*"], // wired keyboard (🖮)
  ["\u{1F5AF}", "*"], // one button mouse (🖯)
  ["\u{1F5B0}", "*"], // two button mouse (🖰)
  ["\u{1F5B3}", "*"], // old personal computer (🖳)
  ["\u{1F5B4}", "*"], // hard disk (🖴)
  ["\u{1F5B5}", "*"], // screen (🖵)
  ["\u{1F5B6}", "*"], // printer icon (🖶)
  ["\u{1F5B7}", "*"], // fax icon (🖷)
  ["\u{1F5B8}", "*"], // optical disc icon (🖸)
  ["\u{1F5B9}", "#"], // document with text (🖹)
  ["\u{1F5BA}", "#"], // document with text and picture (🖺)
  ["\u{1F5BB}", "#"], // document with picture (🖻)
  ["\u{1F5BD}", "#"], // frame with tiles (🖽)
  ["\u{1F5BE}", "#"], // frame with an x (🖾)
  ["\u{1F5BF}", "#"], // black folder (🖿)
  ["\u{1F5C0}", "#"], // folder (🗀)
  ["\u{1F5C1}", "#"], // open folder (🗁)
  ["\u{1F5C5}", "#"], // empty note (🗅)
  ["\u{1F5C6}", "#"], // empty note page (🗆)
  ["\u{1F5C7}", "#"], // empty note pad (🗇)
  ["\u{1F5C8}", "#"], // note (🗈)
  ["\u{1F5C9}", "#"], // note page (🗉)
  ["\u{1F5CA}", "#"], // note pad (🗊)
  ["\u{1F5CB}", "#"], // empty document (🗋)
  ["\u{1F5CC}", "#"], // empty page (🗌)
  ["\u{1F5CD}", "#"], // empty pages (🗍)
  ["\u{1F5CE}", "#"], // document (🗎)
  ["\u{1F5CF}", "#"], // page (🗏)
  ["\u{1F5D0}", "#"], // pages (🗐)
  ["\u{1F5D4}", "#"], // desktop window (🗔)
  ["\u{1F5D5}", "-"], // minimize (🗕)
  ["\u{1F5D6}", "+"], // maximize (🗖)
  ["\u{1F5D7}", "#"], // overlap (🗗)
  ["\u{1F5D8}", "*"], // clockwise right and left semicircle arrows (🗘)
  ["\u{1F5D9}", "X"], // cancellation x (🗙)
  ["\u{1F5DA}", "aA"], // increase font size symbol (🗚)
  ["\u{1F5DB}", "Aa"], // decrease font size symbol (🗛)
  ["\u{1F5DF}", "#"], // page with circled text (🗟)
  ["\u{1F5E0}", "#"], // stock chart (🗠)
  ["\u{1F5E2}", "*"], // lips (🗢)
  ["\u{1F5E4}", "v"], // three rays above (🗤)
  ["\u{1F5E5}", "^"], // three rays below (🗥)
  ["\u{1F5E6}", ">"], // three rays left (🗦)
  ["\u{1F5E7}", "<"], // three rays right (🗧)
  ["\u{1F5E9}", "@"], // right speech bubble (🗩)
  ["\u{1F5EA}", "@"], // two speech bubbles (🗪)
  ["\u{1F5EB}", "@"], // three speech bubbles (🗫)
  ["\u{1F5EC}", "@"], // left thought bubble (🗬)
  ["\u{1F5ED}", "@"], // right thought bubble (🗭)
  ["\u{1F5EE}", "@"], // left anger bubble (🗮)
  ["\u{1F5F0}", "*"], // mood bubble (🗰)
  ["\u{1F5F1}", "*"], // lightning mood bubble (🗱)
  ["\u{1F5F2}", "*"], // lightning mood (🗲)
  ["\u{1F5F4}", "x"], // ballot script x (🗴)
  ["\u{1F5F5}", "x"], // ballot box with script x (🗵)
  ["\u{1F5F6}", "x"], // ballot bold script x (🗶)
  ["\u{1F5F7}", "x"], // ballot box with bold script x (🗷)
  ["\u{1F5F8}", "v"], // light check mark (🗸)
  ["\u{1F5F9}", "v"], // ballot box with bold check (🗹)
  ["\u{1F6C6}", "^"], // triangle with rounded corners (🛆)
  ["\u{1F6C7}", "X"], // prohibited sign (🛇)
  ["\u{1F6C8}", "i"], // circled information source (🛈)
  ["\u{1F6C9}", "m"], // boys symbol (🛉)
  ["\u{1F6CA}", "f"], // girls symbol (🛊)
  ["\u{1F6D3}", "^"], // stupa (🛓)
  ["\u{1F6D4}", "^"], // pagoda (🛔)
  ["\u{1F6E6}", "^"], // up-pointing military airplane (🛦)
  ["\u{1F6E7}", "^"], // up-pointing airplane (🛧)
  ["\u{1F6E8}", "^"], // up-pointing small airplane (🛨)
  ["\u{1F6EA}", "^"], // northeast-pointing airplane (🛪)
  ["\u{1F6F1}", "#"], // oncoming fire engine (🛱)
  ["\u{1F6F2}", "#"], // diesel locomotive (🛲)
];

export type SubstitutionConfig = {
  punctuation?: boolean;
  frames?: boolean;
  shapes?: boolean;
  arrows?: boolean;
  math?: boolean;
  emojis?: boolean;
  stripNonLatin?: boolean;
};

const DEFAULT_CONFIG: Required<SubstitutionConfig> = {
  punctuation: true,
  frames: true,
  shapes: true,
  arrows: true,
  math: true,
  emojis: true,
  stripNonLatin: false,
};

/**
 * Build a combined substitution map from enabled categories.
 */
export function buildSubstitutions(
  config: SubstitutionConfig = {},
): Array<[string, string]> {
  const resolved = { ...DEFAULT_CONFIG, ...config };
  const entries: Array<[string, string]> = [];
  if (resolved.punctuation) entries.push(...PUNCTUATION);
  if (resolved.frames) entries.push(...FRAMES);
  if (resolved.shapes) entries.push(...SHAPES);
  if (resolved.arrows) entries.push(...ARROWS);
  if (resolved.math) entries.push(...MATH);
  if (resolved.emojis) entries.push(...EMOJIS);
  return entries;
}

/**
 * Compile every active key into one global character class of coalesced ranges.
 * A class compiles to a V8 range table; an alternation of 1712 entries drops V8
 * to the interpreter (measured 648 ms vs 0.5 ms per 100 KB of matching text).
 * Ranges may cover unmapped codepoints, which `applySubstitutions` passes
 * through unchanged. An empty set yields `[]`, which never matches.
 */
export function buildRegex(substitutions: Array<[string, string]>): RegExp {
  const points = substitutions
    .map(([ch]) => ch.codePointAt(0)!)
    .sort((a, b) => a - b);
  let pattern = "";
  let i = 0;
  while (i < points.length) {
    if (i > 0 && points[i] === points[i - 1]) {
      i++;
      continue;
    }
    let j = i;
    while (j + 1 < points.length && points[j + 1] === points[j] + 1) j++;
    pattern += escapePoint(points[i]);
    if (j > i) pattern += "-" + escapePoint(points[j]);
    i = j + 1;
  }
  return new RegExp(`[${pattern}]`, "gu");
}

/** Spell a codepoint as an escaped, class-safe literal (`\uXXXX`/`\u{XXXXX}`). */
function escapePoint(cp: number): string {
  const hex = cp.toString(16);
  return cp <= 0xffff ? "\\u" + hex.padStart(4, "0") : "\\u{" + hex + "}";
}

/**
 * Apply substitutions to a string using a pre-built map and regex.
 */
export function applySubstitutions(
  text: string,
  regex: RegExp,
  map: Map<string, string>,
): string {
  return text.replace(regex, (match) => map.get(match) ?? match);
}

// ---------------------------------------------------------------------------
// Allowlist strip
// ---------------------------------------------------------------------------
//
// The kept set is an explicit list of codepoint ranges, not a script query: a
// script filter leaks CJK punctuation and emoji (\p{Script=Common}) and
// fullwidth letters (\p{Script=Latin}).
//
//   U+0000-U+007F  Basic Latin
//   <hole> U+0080-U+009F  C1 controls
//   U+00A0-U+024F  Latin-1 Supplement + Latin Extended-A/B
//   <hole> U+0250-U+1FFF  IPA/Spacing/Combining, scripts, CJK, symbol blocks
//   U+2000-U+200A  General Punctuation, first run
//   <hole> U+200B-U+200F  ZWSP / ZWNJ / ZWJ / LRM / RLM
//   U+2010-U+2027  General Punctuation, second run
//   <hole> U+2028-U+202F  separators, bidi controls, narrow NBSP
//   U+2030-U+205E  General Punctuation, third run
//   <hole> U+205F-U+206F  math space, word joiner, invisible ops, bidi isolates
//
// The General Punctuation holes drop invisible/format characters while keeping
// visible punctuation. Everything else is stripped. This regex only DELETES;
// rewriting `—` to `-` or `✓` to `v` is the tables' job, and they run first.
const NON_ASCII_ALLOWED =
  /[^\u0000-\u007F\u00A0-\u024F\u2000-\u200A\u2010-\u2027\u2030-\u205E]/gu;

/**
 * Remove every character outside the allowlist above. Nothing is folded:
 * fullwidth/halfwidth forms (U+FF00-U+FFEF) are out of scope and are deleted.
 * Applied after substitutions, so curated characters are already ASCII.
 */
export function stripNonLatinChars(text: string): string {
  return text.replace(NON_ASCII_ALLOWED, "");
}
